### ISSUE TITLE
Disable the shadow on the side menu

### ISSUE THREAD

**Issue by pommedeterresautee** [SimonVT/android-menudrawer#10]
Hi,

I want to disable the shadow on the right side of the menu because it doesn't match with the UI of my application. I've searched in resources a png or a drawable to delete. I imagine it is done programmatically. But I've not found where. Can you indicate me a way to do it ?

Thank you.

**Comment by SimonVT** [comment]
You can now disable it through your theme with the mdDropShadowEnabled attribute, or by calling MenuDrawer.setDropShadowEnabled(false).
