### ISSUE TITLE
how to load contents in menudrawer from an activity during runtime??

### ISSUE THREAD

**Issue by pixielot** [SimonVT/android-menudrawer#100]
we are developing a messenger app where we are making use of menudrawer to display the contents of another activity.Is it possible??
We tried calling an activity through intent but there is no connection with the menudrawer created and the class called. is there any way by which we can achieve the connection??
Thank you guys...need of your help ASAP!!

**Comment by SimonVT** [comment]
You can't use activities as content. Use fragments.

**Comment by pixielot** [comment]
Well it's not the question about using fragments or activities. We are using the right menu drawer in the main page of our app and we need the contents of a class to appear in the layout of the menu drawer. is it possible to do that??

**Comment by SimonVT** [comment]
I don't understand the question, you'll have to elaborate.

**Comment by pixielot** [comment]
this is our code snippet and what we are actually trying to do.

public class TextMateMain extends SherlockFragmentActivity{

```
private MenuDrawer rMenu;

@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.text_mate_main);

    /** This is to declare a right menu drawer */
    rMenu=MenuDrawer.attach(this, MenuDrawer.MENU_DRAG_WINDOW,Position.RIGHT);
    rMenu.setMenuView(R.layout.right_menu);
```

}

this is our main class where we make use of the menu drawer.
now we have the layout "right_menu" which should contain the following class codes implemented onto the layout, "right_menu".

public class SelectEmoji extends Activity implements OnItemClickListener {

```
GridView gridemojis;
CustomEmoji cstlistemoji;
TextView tv;
@Override
protected void onCreate(Bundle savedInstanceState) {
    // TODO Auto-generated method stub
    super.onCreate(savedInstanceState);
    setContentView(R.layout.right_menu);
    gridemojis=(GridView)findViewById(R.id.gridView1);
    gridemojis.setOnItemClickListener(this);
    cstlistemoji=new CustomEmoji(this);
    gridemojis.setAdapter(cstlistemoji);
    tv = (TextView)findViewById(R.id.textView1);
    tv.setText("Ola");
}
@Override
public void onItemClick(AdapterView<?> arg0, View arg1, int arg2, long arg3) {
    // TODO Auto-generated method stub
    SharedPreferences myPrefs = this.getSharedPreferences("myPrefs", MODE_WORLD_READABLE);
    SharedPreferences.Editor prefsEditor = myPrefs.edit();
    System.out.println("Emoji is:- " +arg2);
    prefsEditor.putInt("key1", arg2);
    prefsEditor.commit();
    finish();
}
```

}

how can we make the right menu drawer identify this class and display its contents?
please help.

**Comment by SimonVT** [comment]
You can't, as I said it's not possible to use activities as content. Add a fragment to the drawer.
