### ISSUE TITLE
Removing Up Left Arrow when MenuDrawer is Open

### ISSUE THREAD

**Issue by RagingRiver** [SimonVT/android-menudrawer#101]
When the menu drawer is open, the Up ActionBar arrow should be "false" to get better user experience.  When the menu bar is open the Activity icon without the arrow seems more intuitive to close the menu bar.  I tried it out and it feels good to me and I thought you should consider this modification.

**Comment by SimonVT** [comment]
You can remove it if you wish. This is really an implementation detail, not something that's decided by me. In most apps I've seen, the up indicator is always visible. I won't be changing this in the samples.
