### ISSUE TITLE
Fragment is not rendered in a virtual machine of some Honeycomb(3.1 and 3.2).

### ISSUE THREAD

**Issue by jakenjarvis** [SimonVT/android-menudrawer#102]
Hello, SimonVT. I thank you for your wonderful library.
I found MenuDrawer sample is not working.
## RESULT
- Content sample           : work
- ListActivity sample      : _not work_
- Window sample            : work
- ActionBar overlay sample : work
- Right menu               : work
- Top menu                 : _not work_
- Bottom menu              : _not work_
- Touch Mode               : _not work_
- Layout xml               : _not work_
- Static drawer            : _not work_

Fragment of the content area is not drawn.
However, the click event is working. (etc.. ListActivity sample)
It seems to scroll, and arrow is drawn.
## I've done that.
- I have recreated the virtual machine, did not improve.
- I refer to the #17 and #34. However, it did not improve. (android:hardwareAccelerated="true")
- I verified virtual machine 2.3.3 and 4.0.3. no problem.
- I verified GALAXY S2 LTE(SC-03D/4.0.3) and Nexus10(4.2.2). no problem.
## In the following environments, not work.

Android SDK     : r21.1
project library : Android 4.2.2
AndroidManifest : targetSdkVersion=17 / android-support-v4-r12

AVD settings *(Other settings are default.)

VM1

```
10.1 WXGA(Tablet) (1280x800: mdpi)
Android3.2 - API13
RAM:512, VM Heap:32
Storage:200
SD size:64
```

VM2

```
10.1 WXGA(Tablet) (1280x800: mdpi)
Android3.2 - API13
RAM:512, VM Heap:64   (*change)
Storage:200
SD size:64
```

VM3

```
4.7' WXGA(1280x720: xhdpi)   (*change)
Android3.2 - API13
RAM:512, VM Heap:64
Storage:200
SD size:64
```

VM4

```
4.7' WXGA(1280x720: xhdpi)
Android3.1 - API12   (*change)
RAM:512, VM Heap:64
Storage:200
SD size:64
```
## In the following environments, no problem.

Luckily, I found this first.

VM5 : work!

```
4.7' WXGA(1280x720: xhdpi)
Android3.0 - API11   (*change)
RAM:512, VM Heap:64
Storage:200
SD size:64
```

First, I could not believe the VM Heap or Resolution. but, it was not the cause.
When look at the results... 3.1(API12) and 3.2(API13) only?

What problems? Please help me.
thanks

Jaken

**Comment by SimonVT** [comment]
This sounds exclusive to the emulator, same thing happens in the launcher when I run a honeycomb emulator. It's not really something I'm going to spend time on.

**Comment by jakenjarvis** [comment]
Thank you for reply.
Please tell me. This is an issue with the emulator, would not reproduced in the real machine?
Since I did not have the real machine, I was not able to verify.

**Comment by SimonVT** [comment]
I'm assuming it's an emulator issue, since it happens in the launcher as well.
