### ISSUE TITLE
Better touch handling for viewpagers

### ISSUE THREAD

**Issue by venator85** [SimonVT/android-menudrawer#103]
Hi, I'm migrating my app from jfeinstein10's SlidingMenu to MenuDrawer, but I'm having troubles handling viewpager scrolling gestures.

I put together a custom ViewPager subclass which would intercept scrolling gestures towards right only if the current page was not the first (let's assume the menu is on the left side of the screen).

The implementation is available at https://gist.github.com/venator85/4f86f9dae72609e5f0e5

Note that I cannot use the trick in the MenuDrawer ViewPager sample:

```
mMenuDrawer.setTouchMode(position == 0
                            ? MenuDrawer.TOUCH_MODE_FULLSCREEN
                            : MenuDrawer.TOUCH_MODE_NONE);
```

since the ViewPagers in my app are not full-screen.

While this custom viewpager used to work with SlidingMenu, it doesn't work any longer with MenuDrawer.

I see that 2.0.2 introduced the ability to disallow intercepting touch events over certain views, but I would need to take this decision based on the gesture, like how I'm doing in the custom viewpager, rather than on the view being touched.

Do you have any suggestion on how to merge these handling?

Thanks ;)

**Comment by SimonVT** [comment]
I just updated the viewpager sample so it uses the listener to disallow intercepting touch events. This should do what you want.

**Comment by venator85** [comment]
Thanks, that was exactly what I was looking for :)
