### ISSUE TITLE
Left and Right menu drawer

### ISSUE THREAD

**Issue by niqo01** [SimonVT/android-menudrawer#104]
I would like to have a left menu-drawer for my main app navigation and a right one for notifications. (A swiping gesture would only be for closing the drawers)

I have a few questions considering this:
- Is Android-menudrawer the library I should use?
- Is it easy to adapt Android-menudrawer for supporting both left and right at the same time?
- If so, is it something you have considered?

Thanks (again) for this lib

**Comment by SimonVT** [comment]
You might be able to add both a left and a right drawer, but there's no single drawer that has both. It's unlikely I'll be adding this.
