### ISSUE TITLE
Pressing a menu option, close the menu and reload this with other options How I can do?

### ISSUE THREAD

**Issue by rcristobalm** [SimonVT/android-menudrawer#105]
Pressing a menu option, close the menu and reload this with other options How I can do?

Thanks

**Comment by rcristobalm** [comment]
hello, can anyone help?

**Comment by SimonVT** [comment]
The menu and the content area are regular viewgroups. If you want to switch out the views they display, then do just that. There's nothing special to how you do it with this library.
