### ISSUE TITLE
Getting an error while running it on ICS emulator

### ISSUE THREAD

**Issue by gaara87** [SimonVT/android-menudrawer#108]
04-19 20:22:32.465: W/dalvikvm(859): VFY: unable to resolve virtual method 3384: Landroid/view/ViewGroup;.postOnAnimation (Ljava/lang/Runnable;)V

I've been testing it on my jelly bean device till now, but its time to start working on backward compatibility but this is the first error which i'm not able to overcome.

Any idea?

**Comment by SimonVT** [comment]
That's just dalvik complaining that a method doesn't exist. The method isn't actually reached, so it doesn't cause any issues.

**Comment by gaara87** [comment]
04-22 16:01:22.891: I/dalvikvm(478): Could not find method android.view.ViewGroup.postOnAnimation, referenced from method net.simonvt.menudrawer.MenuDrawer.postOnAnimation
04-22 16:01:22.891: W/dalvikvm(478): VFY: unable to resolve virtual method 3385: Landroid/view/ViewGroup;.postOnAnimation (Ljava/lang/Runnable;)V
04-22 16:01:22.891: D/dalvikvm(478): VFY: replacing opcode 0x6f at 0x0006
04-22 16:01:22.911: I/dalvikvm(478): Could not find method net.simonvt.menudrawer.BuildLayerFrameLayout.setTranslationX, referenced from method net.simonvt.menudrawer.LeftDrawer.offsetMenu
04-22 16:01:22.911: W/dalvikvm(478): VFY: unable to resolve virtual method 7641: Lnet/simonvt/menudrawer/BuildLayerFrameLayout;.setTranslationX (F)V
04-22 16:01:22.921: D/dalvikvm(478): VFY: replacing opcode 0x6e at 0x0020
04-22 16:01:22.921: I/dalvikvm(478): Could not find method net.simonvt.menudrawer.BuildLayerFrameLayout.setTranslationX, referenced from method net.simonvt.menudrawer.LeftDrawer.offsetMenu
04-22 16:01:22.921: W/dalvikvm(478): VFY: unable to resolve virtual method 7641: Lnet/simonvt/menudrawer/BuildLayerFrameLayout;.setTranslationX (F)V
04-22 16:01:22.932: D/dalvikvm(478): VFY: replacing opcode 0x6e at 0x0028
04-22 16:01:22.932: D/dalvikvm(478): VFY: dead code 0x002b-002b in Lnet/simonvt/menudrawer/LeftDrawer;.offsetMenu (I)V
04-22 16:01:22.951: I/dalvikvm(478): Could not find method net.simonvt.menudrawer.BuildLayerFrameLayout.setTranslationX, referenced from method net.simonvt.menudrawer.LeftDrawer.onOffsetPixelsChanged
04-22 16:01:22.951: W/dalvikvm(478): VFY: unable to resolve virtual method 7641: Lnet/simonvt/menudrawer/BuildLayerFrameLayout;.setTranslationX (F)V
04-22 16:01:22.961: D/dalvikvm(478): VFY: replacing opcode 0x6e at 0x0007
04-22 16:01:22.961: D/dalvikvm(478): VFY: dead code 0x000a-000f in Lnet/simonvt/menudrawer/LeftDrawer;.onOffsetPixelsChanged (I)V
04-22 16:01:22.991: I/dalvikvm(478): Could not find method net.simonvt.menudrawer.BuildLayerFrameLayout.setLayerType, referenced from method net.simonvt.menudrawer.DraggableDrawer.stopLayerTranslation
04-22 16:01:22.991: W/dalvikvm(478): VFY: unable to resolve virtual method 7639: Lnet/simonvt/menudrawer/BuildLayerFrameLayout;.setLayerType (ILandroid/graphics/Paint;)V
04-22 16:01:22.991: D/dalvikvm(478): VFY: replacing opcode 0x6e at 0x000a
04-22 16:01:22.991: D/dalvikvm(478): VFY: dead code 0x000d-0011 in Lnet/simonvt/menudrawer/DraggableDrawer;.stopLayerTranslation ()V
04-22 16:01:22.991: I/dalvikvm(478): Could not find method android.view.View.getTranslationX, referenced from method net.simonvt.menudrawer.DraggableDrawer.supportGetTranslationX
04-22 16:01:22.991: W/dalvikvm(478): VFY: unable to resolve virtual method 3295: Landroid/view/View;.getTranslationX ()F
04-22 16:01:23.002: D/dalvikvm(478): VFY: replacing opcode 0x6e at 0x0006
04-22 16:01:23.002: D/dalvikvm(478): VFY: dead code 0x0009-000a in Lnet/simonvt/menudrawer/DraggableDrawer;.supportGetTranslationX (Landroid/view/View;)I
04-22 16:01:23.002: I/dalvikvm(478): Could not find method android.view.View.getTranslationY, referenced from method net.simonvt.menudrawer.DraggableDrawer.supportGetTranslationY
04-22 16:01:23.002: W/dalvikvm(478): VFY: unable to resolve virtual method 3296: Landroid/view/View;.getTranslationY ()F
04-22 16:01:23.002: D/dalvikvm(478): VFY: replacing opcode 0x6e at 0x0006
04-22 16:01:23.011: D/dalvikvm(478): VFY: dead code 0x0009-000a in Lnet/simonvt/menudrawer/DraggableDrawer;.supportGetTranslationY (Landroid/view/View;)I
04-22 16:01:23.031: I/dalvikvm(478): Could not find method net.simonvt.menudrawer.BuildLayerFrameLayout.setLayerType, referenced from method net.simonvt.menudrawer.DraggableDrawer.startLayerTranslation
04-22 16:01:23.031: W/dalvikvm(478): VFY: unable to resolve virtual method 7639: Lnet/simonvt/menudrawer/BuildLayerFrameLayout;.setLayerType (ILandroid/graphics/Paint;)V
04-22 16:01:23.031: D/dalvikvm(478): VFY: replacing opcode 0x6e at 0x0013
04-22 16:01:23.031: D/dalvikvm(478): VFY: dead code 0x0016-001a in Lnet/simonvt/menudrawer/DraggableDrawer;.startLayerTranslation ()V
04-22 16:01:23.061: I/dalvikvm(478): Could not find method net.simonvt.menudrawer.BuildLayerFrameLayout.setLayerType, referenced from method net.simonvt.menudrawer.BuildLayerFrameLayout.<init>
04-22 16:01:23.061: W/dalvikvm(478): VFY: unable to resolve virtual method 7639: Lnet/simonvt/menudrawer/BuildLayerFrameLayout;.setLayerType (ILandroid/graphics/Paint;)V
04-22 16:01:23.071: D/dalvikvm(478): VFY: replacing opcode 0x6e at 0x000e
04-22 16:01:23.071: I/dalvikvm(478): Could not find method net.simonvt.menudrawer.BuildLayerFrameLayout.setLayerType, referenced from method net.simonvt.menudrawer.BuildLayerFrameLayout.<init>
04-22 16:01:23.071: W/dalvikvm(478): VFY: unable to resolve virtual method 7639: Lnet/simonvt/menudrawer/BuildLayerFrameLayout;.setLayerType (ILandroid/graphics/Paint;)V
04-22 16:01:23.081: D/dalvikvm(478): VFY: replacing opcode 0x6e at 0x000e
04-22 16:01:23.091: I/dalvikvm(478): Could not find method net.simonvt.menudrawer.BuildLayerFrameLayout.setLayerType, referenced from method net.simonvt.menudrawer.BuildLayerFrameLayout.<init>
04-22 16:01:23.091: W/dalvikvm(478): VFY: unable to resolve virtual method 7639: Lnet/simonvt/menudrawer/BuildLayerFrameLayout;.setLayerType (ILandroid/graphics/Paint;)V
04-22 16:01:23.091: D/dalvikvm(478): VFY: replacing opcode 0x6e at 0x000e

so you are saying that essentially means that dalvik is just complaining of lack of existance of such functions is it?

(Just want to clarify, this drawer works from Api 10 onwards also right? I know it is said to support from 7, but i'm just clarifying anyways)

**Comment by JakeWharton** [comment]
> so you are saying that essentially means that dalvik is just complaining of lack of existance of such functions is it?

Yes. If the code paths where these methods existed was every called it would throw an exception. Since they are not invoked, the fact that Dalvik replaces them with no-ops is of no consequence.
