### ISSUE TITLE
[feature request] ability to show/hide menu without animation

### ISSUE THREAD

**Issue by shaubert** [SimonVT/android-menudrawer#11]
It would be greate open or close the menu without animation. I've found that it's easy to open menu by calling setContentLeft(mMenuWidth). But the opposite call setContentLeft(0) closes menu with animation.

**Comment by SimonVT** [comment]
How are you calling setContentLeft(0)? When the menu is visible, the drawer hijacks all clicks on the content and animates it closed.

**Comment by shaubert** [comment]
I implemented two overload methods: 

```
public void openMenu(boolean withAnimation) {
    if (withAnimation) {
        openMenu();
    } else {
        setContentLeft(mMenuWidth);
    }
}

public void closeMenu(boolean withAnimation) {
    if (withAnimation) {
        closeMenu();
    } else {
        setContentLeft(0);
    }
}
```

openMenu(bool) works great, but closeMenu(bool) fails.

**Comment by SimonVT** [comment]
setContentLeft(0) wont animate it. If, however, you are clicking on the content view when the menu is open, it will animate closed.

**Comment by shaubert** [comment]
sending you a pull request
