### ISSUE TITLE
java.lang.RuntimeException - Canvas: trying to use a recycled bitmap android.graphics.Bitmap@4086fdd8

### ISSUE THREAD

**Issue by dannyroa** [SimonVT/android-menudrawer#113]
Not sure if this is because of MenuDrawer but posting this in case somebody encountered the same.

Stack Trace

---

0   java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@40a7d8b8
1       at android.graphics.Canvas.throwIfRecycled(Canvas.java:955)
2       at android.graphics.Canvas.drawBitmap(Canvas.java:1044)
3       at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:325)
4       at android.view.View.draw(View.java:6865)
5       at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
6       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
7       at android.view.View.draw(View.java:6883)
8       at android.view.View.buildDrawingCache(View.java:6642)
9       at android.view.View.getDrawingCache(View.java:6428)
10      at android.view.ViewGroup.drawChild(ViewGroup.java:1571)
11      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
12      at android.widget.AbsListView.dispatchDraw(AbsListView.java:1506)
13      at android.widget.ListView.dispatchDraw(ListView.java:3227)
14      at android.view.View.draw(View.java:6883)
15      at android.widget.AbsListView.draw(AbsListView.java:2622)
16      at org.holoeverywhere.widget.ListView.draw(ListView.java:314)
17      at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
18      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
19      at android.view.View.draw(View.java:6883)
20      at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
21      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
22      at net.simonvt.menudrawer.BuildLayerFrameLayout.dispatchDraw(BuildLayerFrameLayout.java:77)
23      at android.view.View.draw(View.java:6883)
24      at android.widget.FrameLayout.draw(FrameLayout.java:357)
25      at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
26      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
27      at net.simonvt.menudrawer.DraggableDrawer.dispatchDraw(DraggableDrawer.java:543)
28      at android.view.View.draw(View.java:6883)
29      at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
30      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
31      at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
32      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
33      at android.view.View.draw(View.java:6883)
34      at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
35      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
36      at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
37      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
38      at android.view.View.draw(View.java:6883)
39      at android.widget.FrameLayout.draw(FrameLayout.java:357)
40      at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2106)
41      at android.view.ViewRoot.draw(ViewRoot.java:1562)
42      at android.view.ViewRoot.performTraversals(ViewRoot.java:1298)
43      at android.view.ViewRoot.handleMessage(ViewRoot.java:1911)
44      at android.os.Handler.dispatchMessage(Handler.java:99)
45      at android.os.Looper.loop(Looper.java:130)
46      at android.app.ActivityThread.main(ActivityThread.java:3821)
47      at java.lang.reflect.Method.invokeNative(Native Method)
48      at java.lang.reflect.Method.invoke(Method.java:507)
49      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
50      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
51      at dalvik.system.NativeStart.main(Native Method)

**Comment by SimonVT** [comment]
Line 0 to 19 is all you, I'm afraid :)

**Comment by dannyroa** [comment]
HoloEverywhere is probably doing something different with the ListView.

Thanks.

**Comment by SimonVT** [comment]
You should drop HoloEverywhere and learn the android styling system yourself :) Very few changes are actually needed to make a holo-style theme on older platforms.

**Comment by dannyroa** [comment]
Yeah. I've been encountering a number of side effects with using HoloEverywhere. I went for a quick fix to apply Holo theme. I'll switch out of it soon.
