### ISSUE TITLE
Menu Drawer for a fragment with a view pager inside the fragment

### ISSUE THREAD

**Issue by SoniaMane** [SimonVT/android-menudrawer#115]
I have an activity with FragmentTabHost..I need the menu drawer for the Fragment corresponding to 3rd tab only. And this 3rd Tab Fragment has a view pager in it.Can this be achieved using this library?

**Comment by SimonVT** [comment]
You can use the drawer as any other view.

**Comment by ghost** [comment]
**Hi Simon**, I need to achieve something like this.. but don't know how this is possible.
- **MenuDrawer Item list**
  - _Item Fragment a_
  - _Item Fragment b_
  - _Item Fragment ..._
  - _Item Fragment z_
- **ViewPager**
  - _Fragment a_
  - _Fragment b_
  - _Fragment ..._
  - _Fragment z_

When my app opens, I am on **ViewPager>Fragment a**. Further if swipe from right to left i go to **ViewPager>Fragment b** and so on, back and forth.

Can I _Switch/Navigate_ directly to **Fragment z** or **any other Fragment** inside **ViewPager** using **MenuDrawer**?

I'd Really Appreciate your answer.
Thanks
