### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by nicobo** [SimonVT/android-menudrawer#116]
Hi,

I'm discovering this library and it looks great.

Only it took me some time to understand how to use its features, it would be appreciated to have more online documentation. Adding a short chapter for each demo case would be a great start.

Having Javadoc online would also be a good time saver too.

**Comment by Grantismo** [comment]
+1 document sample installation as well

**Comment by SimonVT** [comment]
There's basic usage in the readme, the samples are all kept relatively simple, and all public methods are documented. I'm probably going to re-do some of the samples and add a bit more description to them, but there's not going to be any online documentation.
