### ISSUE TITLE
Make the duration of the peek action a parameter

### ISSUE THREAD

**Issue by nicobo** [SimonVT/android-menudrawer#117]
This is one of the greatest feature of this library : not having to code the animation to make the drawer discoverable !

It would be useful to be able to change the value of PEEK_DURATION. I've tried a few and I find 2000 ms a good timing for my users.

5000 ms might be ok depending on the target population but it would definitely be a plus to be able to set this parameter to another value.

**Comment by subinsebastien** [comment]
@nicobo +1
