### ISSUE TITLE
Menu drawer sample app not working on Galaxy Tab

### ISSUE THREAD

**Issue by himanshurb** [SimonVT/android-menudrawer#120]
Hi all,

I tried the sample app on Galaxy Tab. Under ListContentSample, the list does not scroll until I toggle the drawer open. 

What must be going off in this case, anyone ?

Thanks,
Himanshu

**Comment by SimonVT** [comment]
Broken device is broken. I think we talked via email. It's a single obsolete device that I don't have myself, so I can't debug this.
