### ISSUE TITLE
setDrawerIndicatorEnabled(false) call causes crash on Gingerbread

### ISSUE THREAD

**Issue by roundhill** [SimonVT/android-menudrawer#121]
I'm getting a crash when setting setDrawerIndicatorEnabled(false) on a gingerbread device. Seems that it doesn't handle the 0 that is passed for the content description:

05-22 10:08:03.232: E/AndroidRuntime(5272): FATAL EXCEPTION: main
05-22 10:08:03.232: E/AndroidRuntime(5272): android.content.res.Resources$NotFoundException: String resource ID #0x0
05-22 10:08:03.232: E/AndroidRuntime(5272):     at android.content.res.Resources.getText(Resources.java:201)
05-22 10:08:03.232: E/AndroidRuntime(5272):     at android.content.res.Resources.getString(Resources.java:254)
05-22 10:08:03.232: E/AndroidRuntime(5272):     at android.content.Context.getString(Context.java:183)
05-22 10:08:03.232: E/AndroidRuntime(5272):     at net.simonvt.menudrawer.compat.ActionBarHelperSherlock.setActionBarUpIndicator(ActionBarHelperSherlock.java:26)
05-22 10:08:03.232: E/AndroidRuntime(5272):     at net.simonvt.menudrawer.compat.ActionBarHelper.setActionBarUpIndicator(ActionBarHelper.java:50)
05-22 10:08:03.232: E/AndroidRuntime(5272):     at net.simonvt.menudrawer.MenuDrawer.setDrawerIndicatorEnabled(MenuDrawer.java:989)

**Comment by SimonVT** [comment]
Thanks, fixed on dev.
