### ISSUE TITLE
StaticMenu and setDrawerIndicatorEnabled(true) lock apps.

### ISSUE THREAD

**Issue by Tolriq** [SimonVT/android-menudrawer#124]
Seems logical but hard to spot since does not crash.

It just goes to an infinite loop trying to animate the icon I guess.

Should perhaps have some sanity checks on this

**Comment by SimonVT** [comment]
Thanks, fixed on dev.

**Comment by Tolriq** [comment]
Thanks to you for being so fast on those 2 :)

250k users can generate quite some mails when something goes wrong :)
