### ISSUE TITLE
How to run this sample

### ISSUE THREAD

**Issue by duanyanrui** [SimonVT/android-menudrawer#128]
I download this code,and import it to eclipse,but i can't to run this sample.

**Comment by DavidTPate** [comment]
Can you provide any error messages or anything? One of the most common problems that I can think of is that this is a library project, so make sure you've imported the library project into Eclipse as well and that it is properly pointing to it as a library project for the sample.

**Comment by duanyanrui** [comment]
Thanks DavidTPate.
The latest version of android-menudrawer has some problem,it was exactly the library issue you mentioned before, but as a plus this new sample also reqired actionbarsherlock which points to another open-source project.Yesterday, I tried use the android-menudrawer-2.0.2,and this version is no problem.
Did you used the latest version of android-menudrawer,Can you tell me how you use it？
