### ISSUE TITLE
View.LAYER_TYPE_HARDWARE and SurfaceView

### ISSUE THREAD

**Issue by shaubert** [SimonVT/android-menudrawer#13]
Hi, Simon. It's me again. I faced with problem when content view with SurfaceView (GLSurfaceView i guess) becomes transparent while sliding. It turns normal when sliding is finished, I've found that this behavior is side effect of forced View.LAYER_TYPE_HARDWARE. If i comment setLayerType() lines the view draws as it should. Can you provide a mechanism to disable LAYER_TYPE_HARDWARE setting.

```
/**
 * If possible, set the layer type to {@link View#LAYER_TYPE_HARDWARE}.
 */
private void startLayerTranslation() {
    if (USE_TRANSLATIONS && !mLayerTypeHardware) {
        mLayerTypeHardware = true;
        mContentView.setLayerType(View.LAYER_TYPE_HARDWARE, null);
        mMenuContainer.setLayerType(View.LAYER_TYPE_HARDWARE, null);
    }
}

/**
 * If the current layer type is {@link View#LAYER_TYPE_HARDWARE}, this will set it to @link View#LAYER_TYPE_NONE}.
 */
private void stopLayerTranslation() {
    if (mLayerTypeHardware) {
        mLayerTypeHardware = false;
        mContentView.setLayerType(View.LAYER_TYPE_NONE, null);
        mMenuContainer.setLayerType(View.LAYER_TYPE_NONE, null);
    }
}
```

**Comment by SimonVT** [comment]
I'll add this, but.. Isn't this how SurfaceView is supposed to work? It pokes a hole through the window

**Comment by SimonVT** [comment]
Added with 19f3e44. Use MenuDrawer#setHardwareLayersEnabled(boolean).

**Comment by shaubert** [comment]
Thanks. The Java Doc for SurfaceView says like you: "the SurfaceView punches a hole in its window to allow its surface to be displayed". The following suggestions are just my guesses. So a SurfaceView is just a hole. The real content draws on a separate window behind the activity's window. The article about Hardware Acceleration describe layer types as: 

```
LAYER_TYPE_NONE: The view is rendered normally and is not backed by an off-screen buffer. 
    This is the default behavior. 
LAYER_TYPE_HARDWARE: The view is rendered in hardware into a hardware texture 
    if the application is hardware accelerated. If the application is not hardware accelerated, 
    this layer type behaves the same as LAYER_TYPE_SOFTWARE. 
LAYER_TYPE_SOFTWARE: The view is rendered in software into a bitmap. 
```

A content of hole-view should be a transparent region. So if we cached such image and draw it later we should get a transparent image placed on activity window. I can't explain why the back window with surface does't visible anymore. Here is a screenshot of what happens https://dl.dropbox.com/u/885571/2012-09-24%2013.26.22.png

**Comment by codezjx** [comment]
I have a similar problem in SlidingMenu, but my issue just appear in  sdk>= 5.0 device. When setsetLayerType(View.LAYER_TYPE_HARDWARE), the surfaceview becomes transparent. lol...
