### ISSUE TITLE
New MenuDrawer.Type.OVERLAY does not work on 2.X

### ISSUE THREAD

**Issue by Tolriq** [SimonVT/android-menudrawer#137]
The menu is always visible on top of the layout and the opening animation does move the menu layout to the right and set the alpha on it.

Tested on emulator 2.2 and 2.3.3

Works ok on all my 4.x devices.

In resume : (Using : MenuDrawer.attach(context, menuType, Position.LEFT, MenuDrawer.MENU_DRAG_CONTENT);
With menu type BEHING or OVERLAY (BEHIND does works ok all os version)
- Drawer closed : The menu is visible over the app no alpha on both the menu and the the app (the menu should be hidden)
- Drawer opened : The app is visible without alpha. The menu has slide to the right and have the alpha on it.

**Comment by SimonVT** [comment]
Fixed and released :)

**Comment by Tolriq** [comment]
Fast and working as usual thanks :)

**Comment by Droidryk** [comment]
any one help to sort out this problem i have also problem menu Drawer is not open on 2.2 on emulator .. i have latest library menu drawer

**Comment by Droidryk** [comment]
toiriq can you some explain how to solve this
