### ISSUE TITLE
Initially no content view; no menu view.

### ISSUE THREAD

**Issue by marcab** [SimonVT/android-menudrawer#138]
As of 50c6afeaa7eb9a21c7a25a3d668f782d1542e886 my content view is initially empty.

Opening the menudrawer will show the content view, but no menu view (though there is a slight 'wiggle' in the content view while attempting to open/close the menudrawer).

Prior to this commit, it worked as expected.

Tested in Android emulator for 2.3 and 4.1.  My app uses ABS 4.3.1.

**Comment by SimonVT** [comment]
I can't reproduce this

**Comment by marcab** [comment]
Fair enough; I'll put up some example code later.

**Comment by marcab** [comment]
Here is a [sample project](https://github.com/marcab/MenuDrawerCheck).

There's almost nothing interesting in it, just a vanilla Activity attaching a MenuDrawer and setting two layout resources.  I even stripped out ABS, but I still can't get it to work after the commit indicated above -- before that commit it works just fine.

Edit: Note that for this example I _do_ see the content view initially (contrary to the title), but from there the behavior is the same.  Trying to open the menudrawer only produces a slight 'wiggle' on my content view.

**Comment by DanielNovak** [comment]
I think this is the same problem I was fighting with for about 3 hours. You have to specify 

```
<style name="AppTheme" parent="AppBaseTheme">
         <item name="menuDrawerStyle">@style/MenuDrawerStyle</item> 
</style>
```

in your base theme. And you NEED to set the drawer width in that style.

```
<style name="MenuDrawerStyle" parent="Widget.MenuDrawer">
    <item name="mdMenuSize">250dp</item>
</style>
```

Otherwise, the width of the menu drawer is 0.

**Comment by lechon** [comment]
Hi, 
I had the version 2.2 and without the style, The menu was working fine. Although now I've changed to the version 3.1 and I have the same problem. I don't like to have to define the Size of the menu. is there any other way to open the menu without write this style "mdMenuSize"?
Thanks,
Jose M¬

**Comment by SimonVT** [comment]
I'm going to assume it's because no menu size has been set. I've defaulted the size to 240dp for all implementations.
