### ISSUE TITLE
TOUCH_MODEL_BEZEL and TOUCH_MODE_NONE is ignored when Type.OVERLAY is used. 

### ISSUE THREAD

**Issue by marcoRS** [SimonVT/android-menudrawer#139]
The touch mode TOUCH_MODEL_BEZEL and TOUCH_MODE_NONE is ignored when set on an overlay menu drawer. It always defaults to TOUCH_MODE_FULLSCREEN.

To reproduce this behavior use: 
MenuDrawer mMenuDrawer = MenuDrawer.attach(this, MenuDrawer.Type.OVERLAY,Position.RIGHT,MenuDrawer.MENU_DRAG_WINDOW);
mMenuDrawer.setTouchMode(MenuDrawer.TOUCH_MODE_BEZEL);

**Comment by Tolriq** [comment]
I use both without any problems, have you check that you do not set the touch mode to fullscreen elsewhere in your code ?

**Comment by SimonVT** [comment]
Can't reproduce this

**Comment by marcoRS** [comment]
The flags worked for me when using the dev branch thanks. Keep up the great work! Your library is extremely useful.
