### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by Tolriq** [SimonVT/android-menudrawer#140]
Hi,

Since I'm preparing release with the new version I discovered that there's now strings in the lib.
And those needs to be translated for release, so what is the correct way to handle this ?

Should all language be added to the lib ?
Is there tools to automatically extract the strings from somewhere ?
Or should I just continue build from sources and add manually the strings for all languages my app support ?

**Comment by SimonVT** [comment]
Just provide your own strings via the `mdDrawerOpenUpContentDescription` and `mdDrawerClosedUpContentDescription` attributes.
