### ISSUE TITLE
pointerIndex out of range. IllegalArgumentException

### ISSUE THREAD

**Issue by marcoRS** [SimonVT/android-menudrawer#141]
I am using the menu-drawer to show a detail view which is a fragment with a layout that has a viewpager and two child fragments. When I start to drag the viewpager to show the next page, if the touch goes past the end of the detail view then I get the illegalArgumentException. 

![device-2013-06-13-191825](https://f.cloud.github.com/assets/507510/652188/bbe9c390-d498-11e2-8e09-31861f6eab52.png)

Here is part of the logcat:

06-13 19:08:10.888: E/AndroidRuntime(22853): FATAL EXCEPTION: main
06-13 19:08:10.888: E/AndroidRuntime(22853): java.lang.IllegalArgumentException: pointerIndex out of range
06-13 19:08:10.888: E/AndroidRuntime(22853):    at android.view.MotionEvent.nativeGetAxisValue(Native Method)
06-13 19:08:10.888: E/AndroidRuntime(22853):    at android.view.MotionEvent.getX(MotionEvent.java:1981)
06-13 19:08:10.888: E/AndroidRuntime(22853):    at net.simonvt.menudrawer.OverlayDrawer.onTouchEvent(OverlayDrawer.java:632)
06-13 19:08:10.888: E/AndroidRuntime(22853):    at android.view.View.dispatchTouchEvent(View.java:7246)
06-13 19:08:10.888: E/AndroidRuntime(22853):    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2168)
06-13 19:08:10.888: E/AndroidRuntime(22853):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1903)
06-13 19:08:10.888: E/AndroidRuntime(22853):    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
06-13 19:08:10.888: E/AndroidRuntime(22853):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)

**Comment by SimonVT** [comment]
Please provide a test case

**Comment by marcoRS** [comment]
Hello Simon, you can download a test project with the setup I'm describing at: https://dl.dropboxusercontent.com/u/9726572/menu-drawer-test.zip

This only happens when i set the MenuDrawer touch mode to TOUCH_MODE_NONE. However if I don't set it to this mode then the ViewPager does not allow for swiping of fragments.

**Comment by SimonVT** [comment]
This is fixed on dev. Implement OnInterceptMoveEventListener and return true if the touch event happens over the ViewPager. You shouldn't have to use TOUCH_MODE_NONE then.
