### ISSUE TITLE
Problems with the API 7 when slide

### ISSUE THREAD

**Issue by lechon** [SimonVT/android-menudrawer#142]
Hi, 
I've just updated to the version 3 and meanwhile I was testing the with the emulator using  API 7, I've found out that the App crash when I slide to open the menu. 
In the library you are using the "getXVelocity" method who was included in the API 8. 

You can find it in the Class SlidingDrawer, method onUpEvent. 

Could you confirm me if that it's a problem because you have declared the minimum SDK version 7?

<uses-sdk android:minSdkVersion="7" android:targetSdkVersion="16" />

the android compatibility library 4 has a new class that allow to access to this methods
VelocityTrackerCompat

https://android.googlesource.com/platform/frameworks/support/+/e4417c91a0bb2fba42a0aaa99edcca1b238af21a/v4/java/android/support/v4/view/VelocityTrackerCompat.java 

thanks,
Jose M¬

**Comment by SimonVT** [comment]
Thanks, fixed on dev
