### ISSUE TITLE
Erratic behavior with dfb7af9

### ISSUE THREAD

**Issue by Tolriq** [SimonVT/android-menudrawer#143]
The last commit dfb7af97b86946052ce8b9e843cc12798fc414c1 finally is not a solution for #56 it creates some really strange behavior :(

I have a custom view in a Viewpager that can have 1 or more page depending on what is happening.

I have set :

```
        mMenuDrawer.setOnInterceptMoveEventListener(new MenuDrawer.OnInterceptMoveEventListener() {
            @Override
            public boolean isViewDraggable(View v, int dx, int x, int y) {
                if (v instanceof SeekBar || v instanceof TouchpadView) {
                    return true;
                }
                return false;
            }
        });
```

Since recently this worked with some bugs unresolved like if you start dragging in the custom view then continue the drag out of the view the menu would show (not wanted behavior of course). (See #56 comments)

Since this commit the result is different depending on cases :

If the ViewPager start with only one page then all works ok, the menu don't show on swipe on the custom view (and now correctly don't show when start in the view and end outside).

But as soon as the viewpager have more than 1 view then swipe over the custom view does directly show the menu like if setOnInterceptMoveEventListener was not set.

If after the ViewPager returns to one page it still have the same bugged behavior (but I guess internally the ViewPager remember it had multiple pages)

**Comment by SimonVT** [comment]
Please provide a test case

**Comment by Tolriq** [comment]
Would a PR on the sample accepted as a test case ?

**Comment by SimonVT** [comment]
Sure :)

**Comment by Tolriq** [comment]
Well after not being able to reproduce it seems it was a ... eclipse problem.

An eclipse clean + ant clean and now all works ok and effectively close #56 don't know what happened.

Just hoping intellij 13 and graddle plugin mature quick enough to switch, too many bug when trying recently :(

Sorry for the noise.
