### ISSUE TITLE
3.0.0 & 3.0.1 do not work (tested on Jelly Bean only)

### ISSUE THREAD

**Issue by Shusshu** [SimonVT/android-menudrawer#145]
I was using 2.0.3 without any problems using an XML layout for the menu and fragments as content for each item.

After upgrading to 3.0.0 & 3.0.1 and changing only 1 line of code : 

```
mMenuDrawer = MenuDrawer.attach(this, MenuDrawer.MENU_DRAG_CONTENG, Position.LEFT);
```

To

```
mMenuDrawer = MenuDrawer.attach(this, MenuDrawer.Type.BEHIND, Position.LEFT, MenuDrawer.MENU_DRAG_CONTENT);
```

The menu drawer didn't work anymore, it didn't show up.
I'm also using the sliding menu indicator and the behavior of the icon was strange, instead of getting smaller it is moving the other way thus leaving a white space between itself and the edge of the screen.

I then installed 3.0.2-SNAPSHOT and everything works well on that build.

Could you please release 3.0.2 ?

**Comment by SimonVT** [comment]
Clean your project, both versions work fine.

**Comment by Shusshu** [comment]
I have cleaned it. (IntelliJ & Maven)

Why would it work on 3.0.2-SNAPSHOT and not the others
