### ISSUE TITLE
[Feature Request] Make dc298f7292 a configurable setting

### ISSUE THREAD

**Issue by Tolriq** [SimonVT/android-menudrawer#146]
Hi,

Can you please consider making the new dc298f7292 (Reveal on touch) an option ?
As I have one some screen some buttons that are quite near the menu and I know users will trigger this from my tests :(

**Comment by SimonVT** [comment]
I'm not interested in making it an option, it's part of the pattern.
It waits 160ms before showing, so touch events should still be delivered to views at the edge. I've just fixed a bug where it would be revealed even if the pointer was released within those 160ms.

**Comment by Tolriq** [comment]
Edit : should learn to read more than what is shown in gmail headers :-) 

Thanks for the fix.

**Comment by Tolriq** [comment]
After test the fix is not enough. It does correct the menu stay on click but not on swipe.

I can reproduce easily in my app swipe in a listview with left inch that can touch the border 
, the menu pop over the list in the semi open state and stay there.

Unable to reproduce for example with google+ and the same gesture.

**Comment by SimonVT** [comment]
Fixed :)

**Comment by Tolriq** [comment]
Works :) Without bugs there's effectively no needs for a settings :p

Sorry for all those reports but my next release is planned for tomorrow and I hate the last minute changes / bug correction that trigger others bugs in an endless loop, specially when on something I don't have control on.

Anyway a big thanks again for all those quick fixes.

**Comment by Tolriq** [comment]
Hi,

Just to inform that now that more than 200k users have updated, there's no crash and no complains on the new default Overlay mode.

So again a big thank you for this library and your time on fixing bugs :)
