### ISSUE TITLE
Actionbarsherlock

### ISSUE THREAD

**Issue by fmartini23** [SimonVT/android-menudrawer#149]
Hi,

If i try add android-menudrawer (sample) in a source (or test sample project) show me.. " Unfortunately, ....ProjectName.... has stopped. :(

Sample: https://github.com/SimonVT/android-menudrawer/blob/master/samples/src/net/simonvt/menudrawer/samples/ActionBarSherlockSample.java

**Comment by SimonVT** [comment]
Works fine here.

**Comment by fmartini23** [comment]
good reply... well, Have any problem with 4.2.2 ? is all ok with this version of android ?
