### ISSUE TITLE
Precision and speed of left menu, behind slower; go to stumble

### ISSUE THREAD

**Issue by rcristobalm** [SimonVT/android-menudrawer#150]
Since I have the version-3.0.2 the menu is slow and low precione to slide.

Especially regularly going to close the menu.

**Comment by SimonVT** [comment]
What does this even mean?

**Comment by rcristobalm** [comment]
when I drag from right to left the drawer of the menu is slow and horns.
Only in the case of left menu behind

**Comment by SimonVT** [comment]
You'll have to provide a sample, I'm not seeing it.

**Comment by rcristobalm** [comment]
How I can make you see it?

**Comment by SimonVT** [comment]
With a sample

**Comment by rcristobalm** [comment]
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.ICE_CREAM_SANDWICH) {
        getActionBar().setDisplayHomeAsUpEnabled(false);
        getActionBar().setHomeButtonEnabled(true);
        getActionBar().setIcon(R.drawable.actionbar_menu);
}
MenuDrawer = MenuDrawer.attach(this, MenuDrawer.Type.BEHIND, Position.LEFT,  
                      MenuDrawer.MENU_DRAG_WINDOW);
mMenuDrawer.setTouchMode(MenuDrawer.TOUCH_MODE_FULLSCREEN);
