### ISSUE TITLE
Run activity after closing menu (animation)

### ISSUE THREAD

**Issue by adek** [SimonVT/android-menudrawer#151]
I'm using Activities in my app. I can't change it to fragment right now. I want to use your library which is great. Everything is working except ... starting new activity from menu drawer. It is very slow.

On menu click I'm using:

mMenuDrawer.closeMenu();
Intent a = new Intent(getApplicationContext(), AddActivity.class);
startActivity(a);

How to start acitivity after menu is closed? I tried "ifs" with mMenuDrawer.isMenuVisible(), isShown but it's now working. 

I've played with drawerState also but without any luck.

**Comment by SimonVT** [comment]
Use OnDrawerStateChangeListener to get notified when it's closed.
