### ISSUE TITLE
Android 2.3 issues (menudrawer) 3.0.2

### ISSUE THREAD

**Issue by adek** [SimonVT/android-menudrawer#152]
I'm testing your library and I was quite happy until I've installed my app on emulator with 2.3 version.

I'm creating sliding menu just like in your example (BaseListSample). I'm using also ActionBarSherlock library. On 4.1+ everything is great. Menu looks and works fine.

In BaseListSample I'm extending not FragmentActivity but SherlockFragmentActivity and I'm using MenuDrawer.Type.OVERLAY.

On 2.3 I've got issues:
- no "hambuger" icon (mMenuDrawer.setSlideDrawable(R.drawable.ic_drawer));
  The drawable is there. Like I said, it works with 4.x. 

You can swipe menu but when you want to scroll it - something strange is going on with styles (colors).

![bad-styling-23](https://f.cloud.github.com/assets/963361/695235/565fd282-dcca-11e2-852f-ae3176a0d48b.png)

**Comment by nseidm1** [comment]
You have the wrong theme set on your application.

"Theme.Sherlock"

**Comment by adek** [comment]
Hmm.. on my app? Or should I set theme for MenuDrawer? 
My app looks good, even on 2.3 devices. The only problem is with MenuDrawer.

And what about second issue? Missing ic_drawer drawable.

**Comment by SimonVT** [comment]
Drawer indicator works in the sample app. You'll have to provide a test case.
Re colors, http://android-developers.blogspot.dk/2009/01/why-is-my-list-black-android.html

**Comment by adek** [comment]
I'm using your Samples right now. I have the same issue. I'm testing it now on my old HTC Desire. While scrolling the list is white.

**Comment by SimonVT** [comment]
I'm not seeing the issue on the 2.1 or 2.3 emulator.

**Comment by adek** [comment]
I'm using your Sample Project, I didn't change anything. The same on emulator + device.
Here's quick video: https://dl.dropboxusercontent.com/u/6838779/VID_20130624_205353.mp4
(sorry for bad quality, recorded few minutes ago)

**Comment by SimonVT** [comment]
So the indicator works fine. The listview behavior is expected, and explained in the link I provided.

**Comment by adek** [comment]
Yes. That's right. Indicator is working on your sample. I need to play with my actionbarsherlock options. 
About listview behavior: I don't understand in 100% is it fixable or not. Reading the article it is. But why don't you put solution in your sample. There are still users using 2.3. 

Quick fix:
mList.setCacheColorHint(Color.parseColor("#00000000"));

Thanks for your answers!
