### ISSUE TITLE
MenuDrawer is not sliding 

### ISSUE THREAD

**Issue by ManojMM026** [SimonVT/android-menudrawer#154]
Hi, I am trying to use add Menu Drawer to my SherlockActivity. When i try to open it using button or swipe gesture it doesnt open. Please help me with this.

here is the code that i am using 

```
             mDrawer =  MenuDrawer.attach(this);

            //this is my activity view
    mDrawer.setContentView(R.layout.activity_default_search_list);

             //this is my menu view
    mDrawer.setMenuView(R.layout.default_search_menudrawer);


    // The drawable that replaces the up indicator in the action bar
    mDrawer.setSlideDrawable(R.drawable.ic_drawer);
    // Whether the previous drawable should be shown
    mDrawer.setDrawerIndicatorEnabled(true);

    mDrawer.peekDrawer();
```

EDIT : I have tested this on Samsung galaxy s3 and on Sony Xperia Tipo both devices shows same result as i mentioned here.

**Comment by SimonVT** [comment]
The samples work, check them to see what you're doing different.
