### ISSUE TITLE
[feature request] Add ability to open menu drawer all the way

### ISSUE THREAD

**Issue by scompt** [SimonVT/android-menudrawer#16]
I have a need for a way for the menu drawer to be animated completely open so that you only see the menu and none of the content view. I want this to be triggered by the user while they're viewing the menu, so there needs to be another `FULLY_OPEN` state in addition to the `OPEN` state.

One way I thought about implementing this would be to allow the content view to be shifted to any arbitrary position (not just 0 and `mMenuWidth`). The menu would then be in the `OPEN` state any time the position of the menu is non-zero. The `OPENING` state would be set any time the menu is animating to the right (like it is now, I think) and `CLOSING` would be set when moving to the left.

Does anyone see a problem with this approach? One issue that comes to mind is that it becomes unclear what opacity the menu overlay should have since the menu width is undefined. The width of the menu view would need to be defined somewhere as well.

**Comment by SimonVT** [comment]
There's still left to be decided how the menu is measured, how touch handling works, etc.. I'm not sure this is ready to be included in the library as a general pattern.
