### ISSUE TITLE
Shadow for StaticDrawer

### ISSUE THREAD

**Issue by noinnion** [SimonVT/android-menudrawer#165]
Is it possible to show the shadow for StaticDrawer?
I tried to setup shadow 

mMenu.setDropShadow(R.drawable.md_shadow);
mMenu.setDropShadowSize(20);
mMenu.setDropShadowEnabled(true);

but it's not working

**Comment by pommedeterresautee** [comment]
@SimonVT I want to let you know that there is a second user interested by this feature :-)

In the portrait view of my application, the Shadow is used to delimit the drawer and the main content screen.

In landscape view, without the shadow I have not anymore this boundary.

In a UI perspective, it s not very consistent.

Regards

**Comment by SimonVT** [comment]
Fixed on dev :)
