### ISSUE TITLE
[Q] Active position on static view (Activity)

### ISSUE THREAD

**Issue by adek** [SimonVT/android-menudrawer#167]
Hi,

This is probably an easy question. I'm using your library and I'm happy with it. The only thing is not working for me (read: probably I'm doing something wrong or it is not possible) is active indicator.

I'm using Activities (I'm planning to migrate with my app to fragments). Is is possible to show indicator as selected on creating acitivy?

I want to open activity and for example - if it's Activity#1 - set active position to item number one etc... I know position of the menu while creating activiy.

For example:
mMenuDrawer.setActiveView(mMenuDrawer.getMenuView(), 1);

is not working.

I'm using menudrawer based on .xml file.

I've checked your sample but I don't know what could be wrong.

**Comment by SimonVT** [comment]
I assume you fixed this. The active view should be a subview of the menu view.

**Comment by adek** [comment]
To be honest. No. As I understand I need to create a new view inside menu view. I coudn't find the right example from your sample.

**Comment by SimonVT** [comment]
You need to pass a view in the menu. The indicator will be drawn next to it.

**Comment by adek** [comment]
Sorry for bumping this thread up.

This is my progress. It is still not working. Like I said. I've got my menu in xml file.

In my Activity, in onCreate function I'm doing something like this:

```
View Subview = mMenuDrawer.getMenuView();
int activeViewID = Subview.findViewById(R.id.item1).getId();
View activeView = findViewById(activeViewID);
    mMenuDrawer.setActiveView(activeView);
```

item1 - is my Textview from MenuView. 

If I add something like this (for test):
activeView.setBackgroundColor(Color.WHITE);

It is changing. And it's working and my item1's background is white. 
Did I forget about something?

**Comment by SimonVT** [comment]
Looks fine to me. Maybe you're not using the theme where you set the indicator drawable or something.

**Comment by adek** [comment]
No. I've checked it. Many times. I've changed for example menu width in this theme - and the menu width is changing.
I've got your indicator drawables and other stuff from example. 

But I'll check if something is wrong again.

My styles:

```
    <style name="MenuDrawer.Widget.Title">
    <item name="android:background">@drawable/md__list_selector_holo_dark</item>
    <item name="android:textAppearance">?android:attr/textAppearance</item>
    <item name="android:textColor">?android:attr/textColorPrimaryInverse</item>
    <item name="android:textSize">18sp</item>
    <item name="android:paddingLeft">16dp</item>
    <item name="android:paddingRight">32dp</item>
    <item name="android:paddingTop">8dp</item>
    <item name="android:paddingBottom">8dp</item>
    <item name="android:drawablePadding">16dp</item>
    <item name="android:gravity">center_vertical</item>
    <item name="android:fontFamily">sans-serif-light</item>

     </style>

    <style name="MenuDrawerStyle" parent="Widget.MenuDrawer">
    <item name="mdActiveIndicator">@drawable/menu_arrow</item>
    <item name="mdMenuSize">250dp</item>
    </style>
```

**Comment by SimonVT** [comment]
You'll have to provide a sample that shows this issue.

**Comment by adek** [comment]
OK. I've modified your sample.
https://dl.dropboxusercontent.com/u/6838779/SampleIndicator.zip

There are 2 files in my sample (res/layout/menu_left_free.xml, ActionBarSherlockSample.java). Overwrite files in menudrawer sample and run your MenuDrawerSamples app. Tap on ActionBarSherlock. 

Indicator should be visible at start (the code is onCreate).

There is also my additional line. If you will uncomment it - you'll see that menu item is changing background.

**Comment by adek** [comment]
Could you take a look at my example? It is based on your Sample app.

Direct links to my files:

My XML layout for menu: 
https://dl.dropboxusercontent.com/u/6838779/menu_left_free.xml

Java:
https://dl.dropboxusercontent.com/u/6838779/ActionBarSherlockSample.java

**Comment by SimonVT** [comment]
Fixed on master

**Comment by adek** [comment]
Working fine now. Thanks!
