### ISSUE TITLE
How to detach menu drawer from activity?

### ISSUE THREAD

**Issue by fraangelini** [SimonVT/android-menudrawer#168]
Hi,
i need to make the menu drawer visible and attached to my activity only after the user is logged in. When the user is logged off (or when the user click on logoff) the menu has to be hidden or detached from my activity.

How can I do it?

Thanks

**Comment by SimonVT** [comment]
You could just set TOUCH_MODE_NONE, that way it can't be dragged open. Otherwise, just remove it like any other View.
