### ISSUE TITLE
Error testing with Activity with MenuDrawer, onMeasure thows IllegalStateException

### ISSUE THREAD

**Issue by ffgiraldez** [SimonVT/android-menudrawer#169]
Using Robolectric 2.1, when i test my Activity with MenuDrawer atached to it using
 MenuDrawer.attach(this, MenuDrawer.Type.BEHIND, Position.LEFT, MenuDrawer.MENU_DRAG_WINDOW);

onMeasure method thows IllegalStateException because height mode don't set to MeasureSpec.EXACTLY

**Comment by SimonVT** [comment]
Any idea what the measure mode is?

**Comment by ffgiraldez** [comment]
Sorry for the delay, the mode for height property is MeasureSpect.AT_MOST .

placing the DragMode to MENU_DRAG_CONTENT works properly and the both eight and weight have MeasureSpect.EXACTLY

**Comment by SimonVT** [comment]
Please try out the current master.

**Comment by ffgiraldez** [comment]
LGFM, the test pass all OK.
