### ISSUE TITLE
Honeycomb Issue - loss of touch events after opening and closing the menu.

### ISSUE THREAD

**Issue by harmanjd** [SimonVT/android-menudrawer#17]
I just found an issue on a Honeycomb tablet. After opening and closing the menu (staying the same activity) the Menu items on the actionbar are no longer clickable. 

I am using android-menudrawer combined with ActionbarSherlcok in this app. 

Has anybody else seen this problem?

**Comment by harmanjd** [comment]
Oh and scrolling doesn't work in the ListView that is part of this activity. It's almost like all touch events (except for the side bar fling and clicking the home icon to open the menu again) become disabled in the app.

**Comment by SimonVT** [comment]
Can you provide a sample that displays this behavior?

**Comment by harmanjd** [comment]
You can see it in the ListSamples activity in the project. If you open and close the menu drawer, you can no longer scroll the list.  

I'll try to put together a sample with the action bar.

**Comment by harmanjd** [comment]
I have been playing with this some more. If I setHardwareLayerEnabled to false for 3.1 emulator - then I don't see this bug. I can still scroll the list after opening and closing the menu.  Going to play with some of the hardware acceleration settings and see if I can find a good combo without turning this off.

**Comment by harmanjd** [comment]
Setting this on the activity or application also seems to solve the problem for Honeycomb:  

android:hardwareAccelerated="true" 

Seems that the hardware acceleration needs to be on, or it needs to be left off or you get this bug.
