### ISSUE TITLE
Problem importing menudrawer library into eclipse

### ISSUE THREAD

**Issue by davideavagliano-zz** [SimonVT/android-menudrawer#170]
Hi all,
For an issue that i can't recognize, when i import the
"android-menudrawer-master" into eclipse (from file > import > existing code into workspace) the library project (and the "samples" also) has several errors into .java files.

Please, help me, i need this library for an important project and i hope someone can help me with this issue.
Thanks,
Davide

**Comment by SimonVT** [comment]
I don't have any errors in the java files.

**Comment by numediaweb** [comment]
Seems beginners like us are not welcomed here :(
No detailed setup tutorial and newbie questions get closed ASAP!

**Comment by SimonVT** [comment]
It's a library project, there's plenty of tutorials on how to use those. If you have some actual issues with the library, that haven't been asked before, feel free to open a proper issue. I'm not going to waste time on stuff like "I have errors in java files" without any additional information.

**Comment by mihai28** [comment]
Hi there,
I had the same issues. If you would have searched in the 'Closed' section, you would have found your answer.
Here is the link:

https://github.com/SimonVT/android-menudrawer/issues/173

**Comment by numediaweb** [comment]
Thanks guys for your support.
I finally got it working in Eclipse by downloading Android 4.1.2 (API 16) from the Android SDK Manager inside Eclipse.. then right click on "menudrawer" project properties and set: Android -> Project Build Target -> Android 4.1.2

[EDIT] A more comprehensive tutorial can be found at: http://www.androidbegin.com/tutorial/implementing-actionbarsherlock-in-android/
