### ISSUE TITLE
Problem changing actionbar background

### ISSUE THREAD

**Issue by dipendrapkrl** [SimonVT/android-menudrawer#172]
In one of my project I have used this library. Since it is targeted for api 16+, I have not used actionbarsherlock library, though this library uses it.
I have overriden one of the method provided in this way:

```
@Override
protected void onMenuItemClicked(int position, Item item) {

    mMenuDrawer.closeMenu();
    if (position == 0) {
        actionBar.setTitle("HOME");
        actionBar.setBackgroundDrawable(getResources().getDrawable(
                R.drawable.header));

    } else if (position == 1) {

        actionBar.setTitle("INBOX");
        actionBar.setBackgroundDrawable(getResources().getDrawable(
                R.drawable.inbox_header));

    } else if (position == 2) {
        actionBar.setTitle("OUTBOX");
        actionBar.setBackgroundDrawable(getResources().getDrawable(
                R.drawable.outbox_header));

    }
    invalidateOptionsMenu(); 
      }
```

I have tested in following devices and the behavior is as follow

 s3(4.2.2) and  s2(4.2.2 custom rom)
 background becomes empty (previous one is removed and new one is not set

 nexus4(4.3)  and samsung galaxy nexus(4.3)
background gets set as expected.

I dont know why this is happenning. 
I tried on another activity that do not extend this library activity and found the behaviour as expected. So, I think there is some problem. Please help me how can I get rid of this problem

Regards,

**Comment by SimonVT** [comment]
If you're wrapping the window, try not doing that. If you're not, it's an issue with something outside the drawer's view hierarchy. Can't do anything about that.
