### ISSUE TITLE
How do I run the sampleApp from version 2.0.3 and above?

### ISSUE THREAD

**Issue by mihai28** [SimonVT/android-menudrawer#173]
Hello,

Can someone please explain how can I run the sample app?
I want to use the library to run wordpress for android, and menudrawer is a prerequisite for it, but the only version of library that I can use is 2.0.2, and it seems this one is to old for wordpress :)

Sample app version 2.0.2 runs ok on emulator and device, no errors are displayed.
But when I import the 2.0.3 version (or any of the above versions, for that matter), I have errors in the library project and in the sample app project.

Every .java file from library is shown with errors.
Are there some prerequisites for version 2.0.3 and above?

I am not saying that your code is not working, just that I can't make it to work.

Many thanks :)

**Comment by SimonVT** [comment]
The samples app depends on the support library and ActionBarSherlock, the library project has no dependencies.

**Comment by mihai28** [comment]
Hi again and thanks for your quick response.
Sorry to insist, but I can't make this issue go away :)

So, the library project has no dependecies (just to be sure, the library project is the [menudrawer] folder in the archive, correct?).
But when I import the library project, every .java file is shown with errors (see the image attached)

Again, sorry to insist, but I tried to make this work for some time, and I feel a little noob for not succeding (I have a feeling the solution is simple, but ....)

Many thanks, again.

![error](https://f.cloud.github.com/assets/5172151/924702/9b8dda60-ff6c-11e2-9116-05ccd064a2ea.png)

**Comment by SimonVT** [comment]
The library is built against API16.

**Comment by DrGasmo** [comment]
@mihai28 This library is setup a little sloppy, and does indeed have API16 dependencies. I ran into your same troubles at first but eventually got it working. Make sure to import only 'menudrawer' into your workspace, and not the root folder that also contains 'menudrawer-samples'. Then you need to open the manifest and set the target to api18. (I changed minimum to 13 but was able to go back to 7). One of the classes, BuildLayerFrameLayout, I believe, needs to have Lint suppressed with @TargetApi(Build.VERSION_CODES.HONEYCOMB_MR1)  a build target. Go ahead and do the entire class, I haven't had any issue yet on API 18 or 9, and I haven't switched to NineOldAndroids yet. Oh and I'm sure you know, grab the .jar from bin and put it in your dependencies. Project -> Clean worked for me and I have a beautiful sliding drawer.

**Comment by JakeWharton** [comment]
> This library is setup a little sloppy.

No it isn't. Eclipse is sloppy.

**Comment by DrGasmo** [comment]
True - got me there.

**Comment by mihai28** [comment]
Hello again,

@SimonVT, changing the target worked (my hunch that the solution was something very, very simple was accurate), thank you for your help.

@DrGasmo, thanks for your response.  I will try and see if those changes will also make it work.

Thanks all of you for your time and support :)
