### ISSUE TITLE
RunTime error: net.simonvt.menudrawer.R$styleable

### ISSUE THREAD

**Issue by kazemnejad** [SimonVT/android-menudrawer#175]
I use SherlockAction bar inside your menu-drawer library.  When i want to run my app , it gets force close. 
i used sample code for SherlockActionbar without any changes. 
so this is cat log
http://pastebin.centos.org/3910/
and activity code:
http://pastebin.centos.org/3913/
Note: i use eclipse and import the menu-drawer library and mark it as library in Project Properties. then add it to my project as a dependency

**Comment by SimonVT** [comment]
It's some issue with your build toold. I've never had this issue, and I don't use Eclipse, so I can't really help you. You'll to google your way to a solution. I know it has happened with other libraries as well (e.g. ActionBarSherlock, probably more hits if you search for issue using its package instead).
