### ISSUE TITLE
TOP + BOTTOM drawer combination not working (works with other combinations though)

### ISSUE THREAD

**Issue by gustiando** [SimonVT/android-menudrawer#176]
I tried it and looks like it doesn't work (it could be me doing something wrong). please take a look at the code:

```
private void attachTopMenuDrawer() {
mMenuDrawerTop = MenuDrawer.attach(mActivity, MenuDrawer.Type.OVERLAY, Position.TOP, MenuDrawer.MENU_DRAG_WINDOW);
mMenuDrawerTop.setContentView(R.layout.activity_movies);
mMenuDrawerTop.setMenuView(R.layout.activity_movies_top_menu);
}

private void attachBottomMenuDrawer() {
mMenuDrawerBottom = MenuDrawer.attach(mActivity, MenuDrawer.Type.OVERLAY, Position.BOTTOM, MenuDrawer.MENU_DRAG_WINDOW);
mMenuDrawerBottom.setContentView(R.layout.activity_movies);
mMenuDrawerBottom.setMenuView(R.layout.activity_movies_bottom_menu);
}
```

I found that any other combination not involving Position.TOP works. why is that? am I missing anything?

By the way, thank you very much for doing such an easy to use lib. this really saved me a lot of time!

**Comment by SimonVT** [comment]
Multiple drawers is not really something I support or test for. If it doesn't work, then that's just how it is. It's not something I'm going to spend time debugging.
Feel free to submit a pull request if there are changes that can be made to support it.
