### ISSUE TITLE
I am a tiro to Android.It have errors when I run the samples .

### ISSUE THREAD

**Issue by xiaobei3120** [SimonVT/android-menudrawer#178]
08-22 15:45:05.135: E/AndroidRuntime(429): FATAL EXCEPTION: main
08-22 15:45:05.135: E/AndroidRuntime(429): java.lang.NoClassDefFoundError: net.simonvt.menudrawer.R$styleable
08-22 15:45:05.135: E/AndroidRuntime(429):  at net.simonvt.menudrawer.MenuDrawer.initDrawer(MenuDrawer.java:550)
08-22 15:45:05.135: E/AndroidRuntime(429):  at net.simonvt.menudrawer.DraggableDrawer.initDrawer(DraggableDrawer.java:174)
08-22 15:45:05.135: E/AndroidRuntime(429):  at net.simonvt.menudrawer.SlidingDrawer.initDrawer(SlidingDrawer.java:32)
08-22 15:45:05.135: E/AndroidRuntime(429):  at net.simonvt.menudrawer.MenuDrawer.<init>(MenuDrawer.java:543)
08-22 15:45:05.135: E/AndroidRuntime(429):  at net.simonvt.menudrawer.MenuDrawer.<init>(MenuDrawer.java:538)
08-22 15:45:05.135: E/AndroidRuntime(429):  at net.simonvt.menudrawer.MenuDrawer.<init>(MenuDrawer.java:534)
08-22 15:45:05.135: E/AndroidRuntime(429):  at net.simonvt.menudrawer.MenuDrawer.<init>(MenuDrawer.java:527)
08-22 15:45:05.135: E/AndroidRuntime(429):  at net.simonvt.menudrawer.DraggableDrawer.<init>(DraggableDrawer.java:157)
08-22 15:45:05.135: E/AndroidRuntime(429):  at net.simonvt.menudrawer.SlidingDrawer.<init>(SlidingDrawer.java:15)
08-22 15:45:05.135: E/AndroidRuntime(429):  at net.simonvt.menudrawer.MenuDrawer.createMenuDrawer(MenuDrawer.java:487)
08-22 15:45:05.135: E/AndroidRuntime(429):  at net.simonvt.menudrawer.MenuDrawer.attach(MenuDrawer.java:452)
08-22 15:45:05.135: E/AndroidRuntime(429):  at net.simonvt.menudrawer.samples.BaseListSample.onCreate(BaseListSample.java:35)
08-22 15:45:05.135: E/AndroidRuntime(429):  at net.simonvt.menudrawer.samples.LeftDrawerSample.onCreate(LeftDrawerSample.java:22)
08-22 15:45:05.135: E/AndroidRuntime(429):  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
08-22 15:45:05.135: E/AndroidRuntime(429):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2627)
08-22 15:45:05.135: E/AndroidRuntime(429):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2679)
08-22 15:45:05.135: E/AndroidRuntime(429):  at android.app.ActivityThread.access$2300(ActivityThread.java:125)
08-22 15:45:05.135: E/AndroidRuntime(429):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2033)
08-22 15:45:05.135: E/AndroidRuntime(429):  at android.os.Handler.dispatchMessage(Handler.java:99)
08-22 15:45:05.135: E/AndroidRuntime(429):  at android.os.Looper.loop(Looper.java:123)
08-22 15:45:05.135: E/AndroidRuntime(429):  at android.app.ActivityThread.main(ActivityThread.java:4627)
08-22 15:45:05.135: E/AndroidRuntime(429):  at java.lang.reflect.Method.invokeNative(Native Method)
08-22 15:45:05.135: E/AndroidRuntime(429):  at java.lang.reflect.Method.invoke(Method.java:521)
08-22 15:45:05.135: E/AndroidRuntime(429):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
08-22 15:45:05.135: E/AndroidRuntime(429):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
08-22 15:45:05.135: E/AndroidRuntime(429):  at dalvik.system.NativeStart.main(Native Method)

**Comment by mariaCP** [comment]
I have the same error, how can I solve it?? thank you!

**Comment by JitenBenzatine** [comment]
Clean your project first and then try to run it again
