### ISSUE TITLE
ActionBarDrawerToggle

### ISSUE THREAD

**Issue by skienzl** [SimonVT/android-menudrawer#179]
have you thought about adding an ActionBarDrawerToggle?

**Comment by xiaobei3120** [comment]
Thanks a lot!
 I adding ActionBarSherlock as lib not ActionBarDrawerToggle,and not errors,and can run,but when click it have errors.

------------------ 原始邮件 ------------------
发件人: "skienzl"; 
发送时间: 2013年8月22日(星期四) 晚上9:06
收件人: "SimonVT/android-menudrawer"; 
主题: [android-menudrawer] ActionBarDrawerToggle (#179)

have you thought about adding an ActionBarDrawerToggle?

**Comment by SimonVT** [comment]
That class is completely pointless. The drawer exposes any methods you need to toggle it.

**Comment by skienzl** [comment]
sorry, i expressed myself in the wrong way. i know that you can easily set it with the actionbar 'up' button. but i think using this button with the back arrow is not the best way to toggle to drawer. i was more thinking about the nice animation of the standard android drawer toggle. would be nice to implement this "drawer toggle icon".

**Comment by SimonVT** [comment]
That's already supported, check the samples.

**Comment by xiaobei3120** [comment]
Thank you very much!
There have no wrong,I delete the MenuDrawLirary's gen folder then clean the project.
I am student,learn Android five month,but I don't know how learn it.I can develop simple APP,and offen read GitHub's hot project,I can use them but I don't know they how achieve,It is very hard to read them for me.How can I improve myself
