### ISSUE TITLE
[Feature request] Both left and right menu drawers

### ISSUE THREAD

**Issue by g123k** [SimonVT/android-menudrawer#18]
Hello,

It would be great if could use simultaneously on the same Activity a LeftDrawer and a RightDrawer.
Simple to ask, maybe be more difficult to implement ;)

**Comment by SimonVT** [comment]
One slide-in menu is already borderline undiscoverable and still remains a design pattern that is in the experimentation phase. Having two doesn't solve any fundamental design need.

**Comment by tasomaniac** [comment]
Just closing it does not help I guess. I was using this lib because I saw Jake Wharton contributing. But I saw other libs allow the drawer to be both left and right. If the developer wants it, why do you restrict it. 

Besides, if you put it to the right and make it open with the overflow menu item, it will be easily discoverable, I guess.

**Comment by tasomaniac** [comment]
FYI The new Google plus update uses both left and right menu drawer.

**Comment by JakeWharton** [comment]
One is window-level the other is content-level.

**Comment by tasomaniac** [comment]
Ok as a result it does that. Simon says it is wrong to do that. Why is it
not an option to add the feature to the library?

**Comment by SimonVT** [comment]
What Jake said. You can't really compare the two. I see no reason you shouldn't be able to achieve the same effect using this library, I just don't support a menu(if you can even call it that) that overlays the content at the . I'm not even sure it's in the scope of the library.

As for a combined left and right drawer, feel free to add one, it's just unlikely I'll be adding it any time soon. I honestly think it'd be much simpler to just nest drawers. If that's not enough, you can, as a start, try and think of what changes to the API are needed to support something like this.

**Comment by tasomaniac** [comment]
Google+ is just updated today. When we talk about this left one was shifting the content and the right menu in Google+ was opening an overlay menu. Now it is the opposite case. You are great developers and I kindly ask your opinion about it. Thank you.

**Comment by savana10** [comment]
![screen shot 2013-07-27 at 02 46 16](https://f.cloud.github.com/assets/3191516/866207/69a48358-f65e-11e2-9486-33c6a3aa30e4.png)
![screen shot 2013-07-27 at 02 46 30](https://f.cloud.github.com/assets/3191516/866208/75a76850-f65e-11e2-9f8a-6aa7cb25ed0c.png)

i tried this and and its working for me
import net.simonvt.menudrawer.MenuDrawer;
import net.simonvt.menudrawer.MenuDrawer.Type;
import net.simonvt.menudrawer.Position;
import android.app.Activity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.Toast;
public class MainActivity extends Activity {

MenuDrawer mDrawer,right;
       Button b,b1;

```
    @Override
    protected void onCreate(Bundle state) {
        super.onCreate(state);


        right = MenuDrawer.attach(this, Type.OVERLAY, Position.LEFT, MenuDrawer.MENU_DRAG_WINDOW);
        right.setContentView(R.layout.activity_main);
        right.setMenuView(R.layout.sliding_menu);
        mDrawer = MenuDrawer.attach(this, Type.OVERLAY, Position.RIGHT, MenuDrawer.MENU_DRAG_WINDOW);
        mDrawer.setContentView(R.layout.activity_main);
        mDrawer.setMenuView(R.layout.sliding_left_menu);
        b=(Button) findViewById(R.id.button1);
        b.setOnClickListener(new View.OnClickListener() {

            @Override
            public void onClick(View v) {
                // TODO Auto-generated method stub
            Toast.makeText(getApplicationContext(), "sample", Toast.LENGTH_SHORT).show();   
            mDrawer.closeMenu();
            }
        });
        b1=(Button) findViewById(R.id.button2);
        b1.setOnClickListener(new View.OnClickListener() {

            @Override
            public void onClick(View v) {
                // TODO Auto-generated method stub
                Toast.makeText(getApplicationContext(), "sample1", Toast.LENGTH_SHORT).show();
                right.closeMenu();
            }
        });

    }
    }
```

able to slide two sides and close when individual button clicked in them

**Comment by andremacpereira** [comment]
Does it still works?

**Comment by subtainishfaq** [comment]
Yes its working @andremacpereira
