### ISSUE TITLE
minsdk 7 seems to be wrong

### ISSUE THREAD

**Issue by alain57** [SimonVT/android-menudrawer#181]
I tried to compile this for an android 4.0 device and i got an error on MenuDrawer.java on this part

```
@Override
public void postOnAnimation(Runnable action) {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
        super.postOnAnimation(action);
    } else {
        postDelayed(action, ANIMATION_DELAY);
    }
}
```

the postOnAnimation method was introduced at API Level 16 so eclipse give me an error on that line

**Comment by SimonVT** [comment]
You need to compile against API16+.
