### ISSUE TITLE
Two menus at a time

### ISSUE THREAD

**Issue by zuinqstudio** [SimonVT/android-menudrawer#182]
Is it possible to create two menus at the same time, on the left and right sides of the screen?

**Comment by savana10** [comment]
yes its possible

**Comment by 35HaRRy** [comment]
How ?

**Comment by savana10** [comment]
https://github.com/SimonVT/android-menudrawer/issues/18#issuecomment-21657235 
check my comment in above link

**Comment by 35HaRRy** [comment]
That's not exactly what I want, but thanks. I want to use Type.BEHIND , like facebook.
