### ISSUE TITLE
Project Errors

### ISSUE THREAD

**Issue by bigbebs** [SimonVT/android-menudrawer#184]
I have downloaded this a few times and tried cleaning the project a few times. In eclipse I keep getting errors in the code, not allowing it to compile. I download it, unzip it, and place it into my workspace. Then in eclipse File>Import>Existing Android Code Into Workspace, check menudrawer and SamplesActivity. I'm not sure if I'm just doing something wrong or whats going on.

**Comment by DrGasmo** [comment]
Need more information on what errors specifically.

**Comment by bigbebs** [comment]
BuildLayerFrameLayout.java
- LAYER_TYPE_HARDWARE cannot be resolved or is not a field
- getLayerType() is undefined

DraggableDrawer.java
- LAYER_TYPE_HARDWARE cannot be resolved or is not a field
- LAYER_TYPE_NONE cannot be resolved or is not a field
- HONEYCOMB cannot be resolved or is not a field
- getTranslationY() is undefined

There are more errors in other files. Seems about half of the files have an error in them.

**Comment by DrGasmo** [comment]
Oh that again. Yeah, it does that on mine too. I change the target to 13 or 18, build, change back to 9 or 7. Should have only one error after that, find it and add an annotation that satisfies the bitch that is eclipse.

**Comment by SimonVT** [comment]
The library is built with API16.
