### ISSUE TITLE
Simple touch triggers opening of sliding menu

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [SimonVT/android-menudrawer#185]
When I set the touch mode to TOUCH_MODE_FULLSCREEN  (for example, in the sample code , inside "left overlay" item) , a single long touch would trigger showing the sliding drawer.

How can I avoid it?

P.S. I'm very new to writing here on Github. Please excuse me if I didn't do it correctly.

**Comment by SimonVT** [comment]
Changed to only reveal when touching edge.
