### ISSUE TITLE
IllegalStateException during activity startup

### ISSUE THREAD

**Issue by shrift** [SimonVT/android-menudrawer#19]
Hi Simon, thanks for this great library!

I got this crash while an activity was starting up (I never saw the activity, it crashed before it rendered)

W/dalvikvm( 8005): threadid=1: thread exiting with uncaught exception (group=0x40eb0300)
E/AndroidRuntime( 8005): FATAL EXCEPTION: main
E/AndroidRuntime( 8005): java.lang.IllegalStateException: This view must be attached to a window first
E/AndroidRuntime( 8005):    at android.view.View.buildLayer(View.java:12109)
E/AndroidRuntime( 8005):    at net.simonvt.widget.BuildLayerFrameLayout$2.run(BuildLayerFrameLayout.java:62)
E/AndroidRuntime( 8005):    at android.os.Handler.handleCallback(Handler.java:615)
E/AndroidRuntime( 8005):    at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 8005):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 8005):    at android.app.ActivityThread.main(ActivityThread.java:4931)
E/AndroidRuntime( 8005):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 8005):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 8005):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
E/AndroidRuntime( 8005):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:558)
E/AndroidRuntime( 8005):    at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  316):   Force finishing activity com.goalworthy.android/.nonui.activities.RecentGoalsActivity_

**Comment by SimonVT** [comment]
Strange, but should be fixed. Thanks for reporting this.

**Comment by shrift** [comment]
Thanks!
