### ISSUE TITLE
Exception java.lang.NoClassDefFoundError: net.simonvt.menudrawer.R$styleable

### ISSUE THREAD

**Issue by mariaCP** [SimonVT/android-menudrawer#193]
Hello, I try your sample. I include the libraries actionBarScherlock and MenuDrawer and it seams ok but, when I try it in my phone, I have this exception if I click one item of the list: 
09-13 16:22:02.921: E/AndroidRuntime(24561): FATAL EXCEPTION: main
09-13 16:22:02.921: E/AndroidRuntime(24561): java.lang.NoClassDefFoundError: net.simonvt.menudrawer.R$styleable
09-13 16:22:02.921: E/AndroidRuntime(24561):    at net.simonvt.menudrawer.MenuDrawer.initDrawer(MenuDrawer.java:550)
09-13 16:22:02.921: E/AndroidRuntime(24561):    at net.simonvt.menudrawer.DraggableDrawer.initDrawer(DraggableDrawer.java:174)
09-13 16:22:02.921: E/AndroidRuntime(24561):    at net.simonvt.menudrawer.SlidingDrawer.initDrawer(SlidingDrawer.java:32)
09-13 16:22:02.921: E/AndroidRuntime(24561):    at net.simonvt.menudrawer.MenuDrawer.<init>(MenuDrawer.java:543)
09-13 16:22:02.921: E/AndroidRuntime(24561):    at net.simonvt.menudrawer.MenuDrawer.<init>(MenuDrawer.java:538)
09-13 16:22:02.921: E/AndroidRuntime(24561):    at net.simonvt.menudrawer.MenuDrawer.<init>(MenuDrawer.java:534)
09-13 16:22:02.921: E/AndroidRuntime(24561):    at net.simonvt.menudrawer.MenuDrawer.<init>(MenuDrawer.java:527)
09-13 16:22:02.921: E/AndroidRuntime(24561):    at net.simonvt.menudrawer.DraggableDrawer.<init>(DraggableDrawer.java:157)
09-13 16:22:02.921: E/AndroidRuntime(24561):    at net.simonvt.menudrawer.SlidingDrawer.<init>(SlidingDrawer.java:15)
09-13 16:22:02.921: E/AndroidRuntime(24561):    at net.simonvt.menudrawer.MenuDrawer.createMenuDrawer(MenuDrawer.java:487)
09-13 16:22:02.921: E/AndroidRuntime(24561):    at net.simonvt.menudrawer.MenuDrawer.attach(MenuDrawer.java:452)
09-13 16:22:02.921: E/AndroidRuntime(24561):    at net.simonvt.menudrawer.samples.BaseListSample.onCreate(BaseListSample.java:35)
09-13 16:22:02.921: E/AndroidRuntime(24561):    at net.simonvt.menudrawer.samples.LeftDrawerSample.onCreate(LeftDrawerSample.java:22)
09-13 16:22:02.921: E/AndroidRuntime(24561):    at android.app.Activity.performCreate(Activity.java:5133)
09-13 16:22:02.921: E/AndroidRuntime(24561):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
09-13 16:22:02.921: E/AndroidRuntime(24561):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
09-13 16:22:02.921: E/AndroidRuntime(24561):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
09-13 16:22:02.921: E/AndroidRuntime(24561):    at android.app.ActivityThread.access$600(ActivityThread.java:141)
09-13 16:22:02.921: E/AndroidRuntime(24561):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
09-13 16:22:02.921: E/AndroidRuntime(24561):    at android.os.Handler.dispatchMessage(Handler.java:99)
09-13 16:22:02.921: E/AndroidRuntime(24561):    at android.os.Looper.loop(Looper.java:137)
09-13 16:22:02.921: E/AndroidRuntime(24561):    at android.app.ActivityThread.main(ActivityThread.java:5103)
09-13 16:22:02.921: E/AndroidRuntime(24561):    at java.lang.reflect.Method.invokeNative(Native Method)
09-13 16:22:02.921: E/AndroidRuntime(24561):    at java.lang.reflect.Method.invoke(Method.java:525)
09-13 16:22:02.921: E/AndroidRuntime(24561):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
09-13 16:22:02.921: E/AndroidRuntime(24561):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
09-13 16:22:02.921: E/AndroidRuntime(24561):    at dalvik.system.NativeStart.main(Native Method)

Can you help me to undestand the problem?

**Comment by rothschild86** [comment]
Just getting started with the library and getting the same error... Any ideas what it could be?

**Comment by jellycookie** [comment]
I got the same error.Any solution?

**Comment by Dreamflying** [comment]
i  didn't find any solution..

**Comment by rothschild86** [comment]
This is a generic problem not related to this library. There is a lot of advice on fixing it. Don't remember what finally helped me, but it was not too complicated. Here's an example: http://javaeesupportpatterns.blogspot.com/2012/06/javalangnoclassdeffounderror-how-to.html

**Comment by rwestergren** [comment]
I resolved this issue by performing a clean on all projects. In Eclipse, Project-> Clean, Clean all projects.

**Comment by xiaomingleng** [comment]
thanks~

2013/12/31 Randy Westergren notifications@github.com

**Comment by DongyangYao666** [comment]
@rwestergren thanks,it's the resolved method.....
