### ISSUE TITLE
Change size of drawer (width)

### ISSUE THREAD

**Issue by evanrich** [SimonVT/android-menudrawer#197]
Is there any way to change the width of the drawer?  I've tried looking in the menu.java and left.java files, but nothing seems to shrink the width.  The listview that gets open is around 285dp wide, I only need it to slide out to around 150dp.  Has anyone figured this out?   I tried manually setting the width of the view i'm inflating, but this doesn't have any bearing.

Thanks!

**Comment by ffmmll** [comment]
you can use mMenu.setMenuSize(xx); to resize the menu :)
