### ISSUE TITLE
AAR artifact

### ISSUE THREAD

**Issue by dant3** [SimonVT/android-menudrawer#201]
Google is constantly improving it's gradle plugin for Android and only option for Gradle users is aar. Maven got aar support too in android-maven-plugin 3.7.0 (which works very well and reduced my build time).

Please, provide aar artifact in maven central.

**Comment by SimonVT** [comment]
There is an aar in central:  http://search.maven.org/#artifactdetails%7Cnet.simonvt.menudrawer%7Cmenudrawer%7C3.0.4%7Capklib

**Comment by dant3** [comment]
Ah, sorry, it looks like I'm blind
