### ISSUE TITLE
Bottom drawer in window-drag mode top padding  defect.

### ISSUE THREAD

**Issue by soarcn** [SimonVT/android-menudrawer#206]
Hi Simon,
Thanks for your excellent library.
There is a defect when using Bottom drawer in window-drag mode. The root cause is at MenuDrawer.java line 1479

I made a quick patch for this.

```
@Override
protected boolean fitSystemWindows(Rect insets) {
    if (mDragMode == MENU_DRAG_WINDOW) {
        if (mPosition==Position.BOTTOM)
            mMenuContainer.setPadding(0, 0, 0, 0);
        else
            mMenuContainer.setPadding(0, insets.top, 0, 0);
    }
    return super.fitSystemWindows(insets);
}
```

BTW: could you please continue support apklib (maven)?

Thanks!

**Comment by SimonVT** [comment]
Makes sense, fixed on master :)

I'm not going to be releasing any more apklibs. It's up to the android maven plugin to support aars.

**Comment by dant3** [comment]
Android maven plugin now fully supports aars (version 3.8.1 is out)
