### ISSUE TITLE
Menu not displaying correctly if not in standard Landscape mode.

### ISSUE THREAD

**Issue by kingargyle** [SimonVT/android-menudrawer#208]
I have an issue reported by a user which is as follows:

If I start in "normal" landscape mode all looks fine. 
Rotating 180° changes nothing so the menu is displayed upside-down.

If I start in "rotated" landscape mode the menu is already upside-down.

So it seems that the library supports only one landscape mode.

This is from github/NineWorlds/serenity-for-android#177 which in issue was reported.   Basically if he is using the tablet in "upside down landscape orientation" the menu isn't rotating to the left side but staying on the right side and according to him upside down.  Is there a setting that I don't have enabled correctly?

**Comment by SimonVT** [comment]
You lock the orientation in standard landscape: https://github.com/NineWorlds/serenity-android/blob/master/serenity-app/AndroidManifest.xml#L52
To support both landscape and reverse landscape in your app you need to use sensorLandscape: https://developer.android.com/guide/topics/manifest/activity-element.html#screen

**Comment by kingargyle** [comment]
Thanks, I figured it was something dumb on my part.
