### ISSUE TITLE
Cant find LAYOUT_DIRECTION_RTL

### ISSUE THREAD

**Issue by inndee** [SimonVT/android-menudrawer#211]
it cant find this variable LAYOUT_DIRECTION_RTL

**Comment by SimonVT** [comment]
It's right here: https://developer.android.com/reference/android/view/View.html#LAYOUT_DIRECTION_RTL
`Added in API level 17`

**Comment by jluther** [comment]
How does that link help that the code won't build because it cannot resolve LAYOUT_DIRECTION_RTL to a variable? I am api level 19.

**Comment by SimonVT** [comment]
If it can't find it then you're not building the library with api level 19.

**Comment by lvitti** [comment]
check if it is correctly added the dependency of android api.
I had the same problem when using maven because in the repositories hasn't the dependencies of the android api 17+

**Comment by jluther** [comment]
Thank you. Even though I have api level 19 installed, the project was defaulting to level 16. 

Does it matter that the AndroidManifest.xml file says that the target sdk version is 16, and not 19? It also says that the minimum version is 7.
