### ISSUE TITLE
MenuDrawer Slider closing problem

### ISSUE THREAD

**Issue by Prem-Tomar** [SimonVT/android-menudrawer#212]
Here is my code

```
    mDrawer = (MenuDrawer) rootView.findViewById(R.id.drawer);
    mDrawer.setTouchMode(MenuDrawer.TOUCH_MODE_BEZEL);

  settingsButton.setOnClickListener(new OnClickListener() {

        @Override
        public void onClick(final View v) {
            // TODO Auto-generated method stub
            ((Swipe) getActivity()).showMenuDrawer(mDrawer);


        }
    });
    contactsButton.setOnClickListener(new OnClickListener() {

        @Override
        public void onClick(final View v) {
            // TODO Auto-generated method stub
            ((Swipe) getActivity())
                    .changeMenuDrawer(mDrawer);


        }
    });


   public void showMenuDrawer(MenuDrawer mDrawer) {
   // mDrawer.setMenuSize(800);
    mDrawer.setMenuView(R.layout.setting_menu_drawer);
    mDrawer.toggleMenu();



   }


    public void changeMenuDrawer(MenuDrawer mDrawer) {
    // mDrawer.setMenuSize(800);
    mDrawer.setMenuView(R.layout.contacts_menu_drawer);


mDrawer.toggleMenu();
 }
```

**Comment by SimonVT** [comment]
Please modify one of the samples so it displays this behavior.

**Comment by Prem-Tomar** [comment]
![open](https://f.cloud.github.com/assets/6422761/1967483/ded302f4-82d5-11e3-97f2-058777f6efb5.png)
![closed](https://f.cloud.github.com/assets/6422761/1967487/eba57caa-82d5-11e3-9d75-da2558a6a414.png)

https://drive.google.com/file/d/0B-cDWQ14KK-_ZzExcTZ3TTlYdFU/edit?usp=sharing

Here is the project folder you can see that happening.

**Comment by SimonVT** [comment]
The content needs a background as it overlays the menu when sliding. Since you set it to transparent, the menu can be seen behind the content.

**Comment by Prem-Tomar** [comment]
I have to use transparent background otherwise all will be worthless for me. Please provide me any solution without removing transparent background.

Thanks

**Comment by Prem-Tomar** [comment]
Needs your help to resolve this issue. It will great for me if you will help me on this issue.

**Comment by SimonVT** [comment]
The content overlays the menu when dragging. If you don't want the menu to be visible behind the content, don't use a transparent background. It's as simple as that.

**Comment by Prem-Tomar** [comment]
I Understand that. but can you please  tell me that where i can handle the animation duration so that i can close that menu quickly so it will be close with the drawer. Because i have limitations that i can not remove transparent background... If you don't mind

Thanks
