### ISSUE TITLE
Library not found when using gradle

### ISSUE THREAD

**Issue by mariomelo** [SimonVT/android-menudrawer#213]
As gradle is the Android new build system, it would be nice if we could use it to find this library.

You just need to change the _packaging_ element on _pom.xml_ to **apklib**, I guess.

**Comment by SimonVT** [comment]
No, gradle uses aar. Menudrawer is already available as an aar in maven central.

**Comment by mariomelo** [comment]
So,

I tried it in my build.gradle:

**compile 'net.simonvt:android-menudrawer:3.0.0@aar'**

But turns out it gives me an error: _Artifact 'net.simonvt:android-menudrawer:3.0.0:android-menudrawer.aar' not found._

Am I doing something wrong?

**Comment by SimonVT** [comment]
You have to use version 3.0.5: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22net.simonvt.menudrawer%22%20AND%20a%3A%22menudrawer%22

**Comment by mariomelo** [comment]
Ok! Thanks! :D
