### ISSUE TITLE
Offtopic: android-numberpicker please release as aar

### ISSUE THREAD

**Issue by rekire** [SimonVT/android-menudrawer#218]
Sorry I know that this here is the wrong repo, but the issue are disabled on the android-numberpicker repo. Could you please upload that lib as aar file?
I get this error when I use the apklib in Android Studio:

> Error: duplicate files during packaging of APK MyProject\build\apk\CycleCalendar-debug-unaligned.apk
> Path in archive: AndroidManifest.xml
> Origin 1:  MyProject\build\libs\CycleCalendar-debug.ap_
> Origin 2: ~.gradle\caches[...]\android-numberpicker-1.0.0.apklib

I guess it would not happen with aar files.
If sombody has an idea how to fix this feel free to comment.

**Comment by SimonVT** [comment]
I have no interest in continuing support of that library, as the readme says.
