### ISSUE TITLE
Menudrawer stuck when opening during content scrolling.

### ISSUE THREAD

**Issue by FGoetzAS24** [SimonVT/android-menudrawer#220]
If i scroll the content and open the menu drawer, during the content is still scrolling, the menu drawer gets stuck (See picture below).

![device-2014-02-14-170629](https://f.cloud.github.com/assets/5583677/2172374/63671572-9592-11e3-9c4b-d2bba1accef9.png)

**Comment by SimonVT** [comment]
Please modify one of the existing samples to display this behavior. I can not reproduce it.

**Comment by FGoetzAS24** [comment]
Thank you for your answer.
Ok. I've modified the sample source code and can reproduce the behaviour.

![device-2014-02-15-192218](https://f.cloud.github.com/assets/5583677/2178574/31f57498-966e-11e3-936b-450deed1ef78.png)

In the activity_contentsample i added a simple ScrollView and changed the MenuDrawer.Type to Overlay.

Changed source code: https://www.dropbox.com/s/of198rajyml5xeg/menudrawer-samples.zip

**Comment by SimonVT** [comment]
Please just fork the repository, update the sample and link the fork. I'm not going to be copying files between projects.

**Comment by FGoetzAS24** [comment]
Sorry, had no git on this machine.
Here it is: https://github.com/FGoetzAS24/android-menudrawer/tree/MenuDrawerStuckBug

**Comment by SimonVT** [comment]
Fixed on master.
