### ISSUE TITLE
ActionBar is removed from ActionBarActivity when attach is called

### ISSUE THREAD

**Issue by abeatte** [SimonVT/android-menudrawer#221]
When using menuDrawer with ActionbarActivity, calling MenuDrawer.attach(this) causes attachToContent to be called. This removes everything in android.R.id.content. For GingerBread devices android.R.id.action_bar is inside android.R.id.content. 

ViewGroup content = (ViewGroup) activity.findViewById(android.R.id.content);
        content.removeAllViews(); // <-- content.getChildren returns a LinearLayout       //containing android.R.id.action_bar, a FrameLayout for the content, and //android.R.id.split_action_bar. 
        content.addView(menuDrawer, LayoutParams.MATCH_PARENT, LayoutParams.MATCH_PARENT);

**Comment by SimonVT** [comment]
Yeah, google broke the API. I'm not going to handle this in any way, add the drawer in your layout resource instead.

**Comment by abeatte** [comment]
Hey @SimonVT, thanks. How would I go about doing that? I tried doing it similar to how the NavigaitonDrawer is added and I got an instantiationException. Am I missing something?

**Comment by SimonVT** [comment]
There's a sample that shows how to use the drawer in layouts.

**Comment by abeatte** [comment]
Oh, great. I didn't see that one. Fantastic work. Thanks!
