### ISSUE TITLE
i want to change background color in MenuDrawer,how to do?

### ISSUE THREAD

**Issue by icebound1** [SimonVT/android-menudrawer#225]
i want to change background color in MenuDrawer,how to do?
merci

**Comment by SimonVT** [comment]
You can use the mdContentBackground and mdMenuBackground attributes: https://github.com/SimonVT/android-menudrawer/blob/master/menudrawer/res/values/attrs.xml#L10

**Comment by icebound1** [comment]
please give me a example，merci

**Comment by TheAnimatrix** [comment]
yea pls an example would help
