### ISSUE TITLE
Change menu height

### ISSUE THREAD

**Issue by MarkySmarky** [SimonVT/android-menudrawer#226]
Hey man, how is it going?
How can I change the height of a right side menu drawer?
I'm not using any action bar (v4 support lib/sherlock/etc...) but I do have my own layout as an action bar. All I want to do is to set my right side (screen right - opens from right to left) menu to be below my own custom action bar. Can't find it inside your code.

Is it possible?

Thanks!

**Comment by SimonVT** [comment]
Left/right menus will always be the entire height of the MenuDrawer view.
You can add the drawer in your xml layout below your custom action bar. [This](https://github.com/SimonVT/android-menudrawer/blob/master/menudrawer-samples/res/layout/activity_layoutsample.xml) sample shows how to do this.

**Comment by MarkySmarky** [comment]
The example shows menu drawer as the root, with menu and content as children.
My action bar is part of the content, and cannot be separated from there. So it's not possible for me to set the menu to be below the action bar. I've been using your library for some time now and don't want to replace it, so how can still make it happen?

**Comment by SimonVT** [comment]
The example shows how to use the drawer in XML. Where in your XML you place
it is up to you - it works just like any other view.

**Comment by MarkySmarky** [comment]
I understand what you're saying but in my case, I cannot have the content below my action bar but I do have to have the menu below the action bar. that's why I need some way to control the height of the menu....

**Comment by SimonVT** [comment]
It doesn't force you to do anything, it's just a regular ViewGroup.

**Comment by MarkySmarky** [comment]
I have the root as net.simonvt.menudrawer.OverlayDrawer.
it has 2 relative layouts in it - mdContent and mdMenu.
Once I add another element as siebeling (with some ID) it crashes with:

03-13 09:51:16.886: E/AndroidRuntime(9482): Caused by: java.lang.IllegalStateException: Menu and content view added in xml must have id's @id/mdMenu and @id/mdContent
03-13 09:51:16.886: E/AndroidRuntime(9482):     at net.simonvt.menudrawer.MenuDrawer.onFinishInflate(MenuDrawer.java:631)
03-13 09:51:16.886: E/AndroidRuntime(9482):     at android.view.LayoutInflater.rInflate(LayoutInflater.java:774)
03-13 09:51:16.886: E/AndroidRuntime(9482):     at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
03-13 09:51:16.886: E/AndroidRuntime(9482):     at android.view.LayoutInflater.inflate(LayoutInflater.java:398)

**Comment by SimonVT** [comment]
The MenuDrawer view can only have two direct children, mdContent and mdMenu.

**Comment by MarkySmarky** [comment]
That's exactly what I'm saying.... i can only have 2 children - content and menu.
Once my own custom action bar layout is A PART of the content itself, how can I tell the menu to be BELOW it visually (like I have a real action bar)??

1 root - Overlay layout
2 children - relative layouts
        \* the first is content (with the webview and custom "action bar" layout)
        \* the second is menu with a listview in it

I want to have the listview in the menu to be below the "action bar" in the content....
It is not possible in the way you're saying.
What kind of layout should I have for example to make it work despite the fact that content and menu must be siblings.

pleasssseeee.....

**Comment by SimonVT** [comment]
1 root - vertical linearlayout
2 siblings - your actionbar and the overlay drawer

**Comment by MarkySmarky** [comment]
must have the content behind the action bar, and the menu below it.

**Comment by SimonVT** [comment]
Then overlay the actionbar on the drawer and set a margin on the view you
put in the menu.

**Comment by MarkySmarky** [comment]
thanks man! it worked..... but - the menu content does have a margin from top as i asked but the menu itself still can be seen behind my action bar (which is a bit transparent)

**Comment by SimonVT** [comment]
Remove the background with the mdMenuBackground attribute and set your own.
The viewgroup the overlay drawer moves will always match the height.

**Comment by MarkySmarky** [comment]
works man! you're a king! thanks.
