### ISSUE TITLE
Give the user a quick peek at touch interaction

### ISSUE THREAD

**Issue by nailgilaziev** [SimonVT/android-menudrawer#229]
From Android developers:
If the user touches the very left edge of the screen (within 20 dp from the left), have the drawer peek out as soon as the finger makes contact with the display. This promotes accidental discovery and provides richer feedback.
The navigation drawer peeks out when the user touches the very left edge of the screen.

The same behavior would like to see here.

Interaction with a NavigationDrawer more convenient, especially if the content is a map.
Comfort is not due to peek functionality, but because of advanced animation - you put your finger and menu began to slide and after you go to open a menu on

**Comment by SimonVT** [comment]
This already happens with the overlay drawer. I decided against adding it when the drawer is behind the content.
