### ISSUE TITLE
Control Peek Height (bottom overlay drawer) 

### ISSUE THREAD

**Issue by MarkySmarky** [SimonVT/android-menudrawer#230]
How to set the peek height when using a bottom overlay drawer? I'm using peekDrawer(0,0) method. 
Can it be done?
Thanks.

**Comment by MarkySmarky** [comment]
Can it be done?

**Comment by SimonVT** [comment]
No, this is not possible.

**Comment by MarkySmarky** [comment]
is there anything that can be done with mPeekSize on OverlayDrawer?

**Comment by SimonVT** [comment]
There's no API to change the peek size. I have no interest in adding it myself, so someone would have to supply a pull request.
