### ISSUE TITLE
Menu has artefacts on window with surface view on HTC Sense 2.3

### ISSUE THREAD

**Issue by shaubert** [SimonVT/android-menudrawer#24]
Hi.

On Android 2.3 on HTC Sence device the menu draws incorrectly. When you open the menu a part of it remains black. It seems like a surface "hole" not moved when you just call offsetLeftAndRight(). requestLayout() call fixes the problem. 

```
@Override
protected void onOffsetPixelsChanged(int offsetPixels) {
    if (USE_TRANSLATIONS) {
        mContentView.setTranslationX(offsetPixels);
        offsetMenu(offsetPixels);
        requestLayout();
        invalidate();
    } else {
        mContentView.offsetLeftAndRight(offsetPixels - mContentView.getLeft());
        offsetMenu(offsetPixels);
        requestLayout();
        invalidate();
    }
}
```

**Comment by SimonVT** [comment]
I'm not sure there's anything I can do about this. SurfaceView is kind of an "edge case", that I'd rather not sacrifice performance for. I'm just gonna close this until someone comes up with a great way of solving this.

**Comment by groodt** [comment]
I'm using this to solve my problem:
https://gist.github.com/groodt/5181980

**Comment by rubdottocom** [comment]
@groodt I'm gonna kiss you!

**Comment by groodt** [comment]
:) Awwww shucks! It is kind of janky, but hope it solves your immediate problem. Seems to work fine in the places I implemented it.
