### ISSUE TITLE
why it's deprecated?

### ISSUE THREAD

**Issue by billhsu** [SimonVT/android-menudrawer#259]
And what's the replacement?

**Comment by GMetaxakis** [comment]
i think android.support.v4.widget.DrawerLayout

**Comment by billhsu** [comment]
make sense.

**Comment by GMetaxakis** [comment]
but i prefer to use that library, the google one i couldn't make it to work from eclipse and i don't like android studio.

**Comment by billhsu** [comment]
I prefer android studio actually. It's much more convenient than eclipse.

**Comment by SimonVT** [comment]
Yeah, the replacement is DrawerLayout. If I continued development, I'd basically just be duplicating behavior.
