### ISSUE TITLE
Release to Maven Central

### ISSUE THREAD

**Issue by kevinsawicki** [SimonVT/android-menudrawer#28]
Would be nice to have a release in there even if it is pre-1.0

**Comment by SimonVT** [comment]
I'll consult my local maven guru, see if I can get this done.

**Comment by kevinsawicki** [comment]
1.0.0 has been released to [Maven Central](http://search.maven.org/#artifactdetails%7Cnet.simonvt%7Candroid-menudrawer%7C1.0.0%7Capklib).

**Comment by SimonVT** [comment]
Ah right, forgot to close it :) Thanks
