### ISSUE TITLE
mDrawerState doesn't changed to STATE_DRAGGING on onInterceptTouchEvent()

### ISSUE THREAD

**Issue by shaubert** [SimonVT/android-menudrawer#3]
There is no mDrawerState change when start dragging a content window. OnDrawerStateChangeListener is notified only after removiing a finger. I suppose that this is due the issue at the following code from onInterceptTouchEvent():

case MotionEvent.ACTION_MOVE:
    ...
    if (allowDrag) {
        mIsDragging = true;
...
    }

mIsDragging is set to true, but mDrawerState doesn't changed to STATE_DRAGGING.

**Comment by SimonVT** [comment]
It should work now.
