### ISSUE TITLE
ListView stop working after openning the MenuDrawer

### ISSUE THREAD

**Issue by JafarKhQ** [SimonVT/android-menudrawer#34]
In the ListActivity Sample, after opining the MenuDrawer the ListView will stop scrolling and the istviewItem will not get highlighted when you click on it, however the itemClickLstener gets fired (toast appear)

steps:
 1- run MenuDrawerDemo
 2- go to ListActivity Sample
 3- scroll listView or click on any item (its working fine)
 4- open the MenuDrawer
 5- try to scroll the listView (not scrolling), click on any listViewItem (the cell will not highlight but the toast will appear)

device 1: galaxy Tab 7.7 (GT-P6800) run Honeycomb 3.2
device 2: emulator run Android 3.2

I think its a Honeycomb Bug.

**Comment by harmanjd** [comment]
Jafar,

I reported this a while ago and found some good workarounds.  See https://github.com/SimonVT/android-menudrawer/issues/17.  

Basically the issue has to do with turning on and off hardware acceleration in honeycomb. The way to get around it is to turn on hardware acceleration for you app (it is enabled by default in ICS, but NOT honeycomb) OR you can disable it on the menudrawer (see MenuDrawer.setHardwareLayerEnabled). I chose the former for my app, but either seemed to work.

**Comment by JafarKhQ** [comment]
I applied "android:hardwareAccelerated="true"" for the Activity and its work.
Thank you.
