### ISSUE TITLE
[Feature Request] Add a setter for MAX_DRAG_BEZEL_DP

### ISSUE THREAD

**Issue by Tolriq** [SimonVT/android-menudrawer#36]
Hi,

First thanks for your wonderfull lib.

Some of my users use covers for their phones / tablets that goes up to the border of the touch area and the default value of 24dp does not permit them to start the bezel swipe to show the menu.

Adding a new setter to configure this value would correct this.

Thanks,
Tolriq.

**Comment by ghost** [comment]
@Tolriq has a valid point. Having a getter would be a nice idea for devs to specify their own bezel swipe limit.

**Comment by ghost** [comment]
Typo - getter - setter.

**Comment by Tolriq** [comment]
Any news on that ? Would a PR be accepted ?

**Comment by SimonVT** [comment]
Added to dev branch, MenuDrawer#setTouchBezelSize(int).
