### ISSUE TITLE
Maven Dependency

### ISSUE THREAD

**Issue by ghost** [SimonVT/android-menudrawer#39]
Adding the android-menudrawer library as a maven dependency.

```
<dependency>
            <groupId>net.simonvt</groupId>
            <artifactId>android-menudrawer</artifactId>
            <version>1.0.0</version>
            <type>apklib</type>
</dependency>
```

The library is downloaded from the Central Repository in 

> target/unpack/apklibs/net.simonvt_android-menudrawer_apklib_1.0.0

The target in it's project.properties is

> # Project target.
> 
> ```
> target=android-8
> ```

It should be 16.

**Comment by ghost** [comment]
Also,

> android.library=true

is missing.

**Comment by JakeWharton** [comment]
Maven doesn't use `project.properties`.

**Comment by JakeWharton** [comment]
There's no `project.properties` in the apklib deployed to central. This is being generated by your tooling based off of some local configuration.
