### ISSUE TITLE
Progress Dialog on SideMenu

### ISSUE THREAD

**Issue by rfmussa** [SimonVT/android-menudrawer#42]
Hello, how can I show a progress dialog inside the sidemenu(Like facebook does on its right sidemenu).

Thank you

**Comment by JakeWharton** [comment]
Place a `<ProgressBar>` in the layout that you use inside the drawer. A common pattern is to use a `ViewAnimator` as the parent with a `ProgressBar` and your actual content view as its children. Then you can flip between the two using the `ViewAnimator`'s API.

**Comment by rfmussa** [comment]
thats it thanks!
