### ISSUE TITLE
Option to Keep the menu open all the time for landscape position

### ISSUE THREAD

**Issue by pommedeterresautee** [SimonVT/android-menudrawer#43]
Right now, we need to use a second layout with a new listview to get this possibility. I am emulating the arrow on the right side, ect...

It would be better if it s implemented directly in the library.

The bezier movement would be locked too

**Comment by tasomaniac** [comment]
I am doing the same thing on the tablet layout. It would be very very great to have this feature implemented. Thank you.

**Comment by SimonVT** [comment]
Added on dev.

**Comment by tasomaniac** [comment]
You are great.

**Comment by pommedeterresautee** [comment]
Current implementation is not working during rotation :-(
