### ISSUE TITLE
Background problem when scrolling listview

### ISSUE THREAD

**Issue by tasomaniac** [SimonVT/android-menudrawer#47]
First I must tell you that 1 year ago, users with HTC Desire had similiar problem with my application. The listview background was all white on their problem and I could find the solution to that.

In you library, I have a similiar problem as you can see in the images below
![Image with normal ListView](https://f.cloud.github.com/assets/763339/4496/367717b6-4312-11e2-8507-b4b3a026a14f.png)
![It becomes like this when I touch it.](https://f.cloud.github.com/assets/763339/4497/3ab1a38c-4312-11e2-9af1-64fe00545866.png)

I am using Motorola Atrix here. Atrix and MotoBlue UI has these kind of problems and I published my update. After couple of days my users complaint about this. Lots of users had this issue. And after that, I have published another update with using MenuScrollView with only TextViews in it. The problem is resolved now but I want to use ListView in my menudrawer. 

What do you say? Thank you.

**Comment by SimonVT** [comment]
The samples included are only intended to showcase how to use the library, not how to properly use stuff like listview, etc. However, what you're experiencing is probably just android:cacheColorHint. If not, you'll have to figure out a solution yourself.
