### ISSUE TITLE
Api target problem for Honeycomb

### ISSUE THREAD

**Issue by Tolriq** [SimonVT/android-menudrawer#51]
Hi,

There's a problem in current 1.0 about `android.view.View.buildLayer()` in `BuildLayerFrameLayout`

You call this function if `MenuDrawer.USE_TRANSLATIONS` is set but you set this bool with :

`static final boolean USE_TRANSLATIONS = Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB;`

But this function is API level 12 so should be `Build.VERSION_CODES.HONEYCOMB_MR1`

**Comment by SimonVT** [comment]
Thanks! Fixed on dev branch.
