### ISSUE TITLE
UI bug in Gingerbread when menu is scrolled

### ISSUE THREAD

**Issue by timekillerj** [SimonVT/android-menudrawer#52]
Hello, I discovered this bug today and confirmed it on 2 physical gingerbread devices, and 1 emulator. It may affect Froyo and older devices as well, but I did not test.

When scrolling the sliding menu, the entire background goes white. Sometimes it goes back to normal once finished scrolling, but not always.

To reproduce: open the included samples and add enough Items to cause the menu to scroll. Try scrolling.

Example, open ViewPagerSample.java and add these menu items:

```
    List<Object> items = new ArrayList<Object>();
    items.add(new Item("Item 1", R.drawable.ic_action_refresh_dark));
    items.add(new Item("Item 2", R.drawable.ic_action_select_all_dark));
    items.add(new Category("Cat 1"));
    items.add(new Item("Item 3", R.drawable.ic_action_refresh_dark));
    items.add(new Item("Item 4", R.drawable.ic_action_select_all_dark));
    items.add(new Category("Cat 2"));
    items.add(new Item("Item 5", R.drawable.ic_action_refresh_dark));
    items.add(new Item("Item 6", R.drawable.ic_action_select_all_dark));
    items.add(new Item("Item 7", R.drawable.ic_action_refresh_dark));
    items.add(new Item("Item 8", R.drawable.ic_action_select_all_dark));
    items.add(new Category("Cat 3"));
    items.add(new Item("Item 9", R.drawable.ic_action_refresh_dark));
    items.add(new Item("Item 10", R.drawable.ic_action_select_all_dark));
    items.add(new Category("Cat 4"));
    items.add(new Item("Item 11", R.drawable.ic_action_refresh_dark));
    items.add(new Item("Item 12", R.drawable.ic_action_select_all_dark));
    items.add(new Item("Item 13", R.drawable.ic_action_refresh_dark));
    items.add(new Item("Item 14", R.drawable.ic_action_select_all_dark));
    items.add(new Category("Cat 5"));
    items.add(new Item("Item 15", R.drawable.ic_action_refresh_dark));
    items.add(new Item("Item 16", R.drawable.ic_action_select_all_dark));
    items.add(new Category("Cat 6"));
    items.add(new Item("Item 17", R.drawable.ic_action_refresh_dark));
    items.add(new Item("Item 18", R.drawable.ic_action_select_all_dark));
```

Launch the app, open the example, scroll the menu.

**Comment by SimonVT** [comment]
That's because it's a listview: http://android-developers.blogspot.com/2009/01/why-is-my-list-black-android.html

**Comment by kenyee** [comment]
Simon: is there a workaround?  I didn't realize my bug was a dup...sorry.
I'll try the disabling the cache color hint when I get back later.

**Comment by SimonVT** [comment]
It's just how listview works, you have to set cachecolorhint.

**Comment by kenyee** [comment]
I can confirm that adding 
   android:cacheColorHint="#00000000"
to my listview fixed my issue.

You might want to do that with the static drawer sample in the menudrawer sample app though...if I scroll that on my Android 2.1 device, the menu turns into a white rectangle that only shows the Cat1/Cat2/Cat3 text sometimes...

Thanks, Simon.
