### ISSUE TITLE
Menu drawer is higlighting all items on the list on scroll

### ISSUE THREAD

**Issue by akemalfirdaus** [SimonVT/android-menudrawer#53]
I am not sure how to say this but every time when I try to scroll the list, the item will all be highlighted making all the text invisible until the user clicks on one of the item.

**Comment by ghost** [comment]
Duplicate of #52 

@SimonVT : That's because it's a listview: http://android-developers.blogspot.com/2009/01/why-is-my-list-black-android.html

**Comment by akemalfirdaus** [comment]
@iontech On which file do I edit the code? Because none of the XML Layouts I am using contains ListView, only TextView and Layouts.

**Comment by ghost** [comment]
@akemalfirdaus What list do you have, then?

**Comment by akemalfirdaus** [comment]
@iontech whoops my bad there was a list, but it was put there programmatically. Didn't notice before. So that fixed it.

**Comment by ghost** [comment]
Cool. :smiley:
