### ISSUE TITLE
How to configure right offset (visible part of content) when menu is open?

### ISSUE THREAD

**Issue by lexer** [SimonVT/android-menudrawer#55]
How to configure right offset (visible part of content) when menu is open?

**Comment by lexer** [comment]
I was able to solve this: 

Display display = getWindowManager().getDefaultDisplay();
menuDrawerManager.getMenuDrawer().setMenuWidth(display.getWidth() - metricsUtils.dpToPixels(48));

Is there any direct way to set offset?

**Comment by SimonVT** [comment]
No, there's no direct way to set it. I decided it made more sense to set the menus width explicitly, since the menus content is mostly fixed size. You wouldn't want it to cover most of the screen e.g. in landscape or on a tablet, as you would on a phone in portrait.
