### ISSUE TITLE
[Feature Request] Add a way to have "holes" in TOUCH_MODE_FULLSCREEN

### ISSUE THREAD

**Issue by Tolriq** [SimonVT/android-menudrawer#56]
Hi,

It would be cool if there's an easy way to disable the allowdrag for certain zone when in TOUCH_MODE_FULLSCREEN.

For Viewpager for example we can override canScroll.

This may be needed for screen that contains seekbar or custom gesture zone that currently can't pass over this menu.

I think the same way as viewpager would be enough.

**Comment by SimonVT** [comment]
As far as I can see the ViewPager method only works on api14+. I could add it, but an alternative method would probably be preferred.

**Comment by Tolriq** [comment]
Well I use ViewPager from SupportLibrary and it seems to support the canScroll for every api level.

Where did you see this limit ?

**Comment by SimonVT** [comment]
The fact that canScroll calls View#canScrollHorizontally on ICS, and returns false on all other api levels

**Comment by Tolriq** [comment]
Ho yes but the most common solution is to override the canScroll and do things like 

```
if (v instanceof SeekBar) {
      return true;
}
```

I was not even aware of the integrated subcall.

During my search for this problem for ViewPager I did not find any other satisfying solution.

Adding the canScroll in MenuDrawer and allow overriding it seems to me like an acceptable solution. Will work natively for ICS and can be corrected for before or for Custom Views / needs that does not implement the canScroll.

**Comment by SimonVT** [comment]
Ah, I see. I could probably add some kind of callback.

**Comment by SimonVT** [comment]
Added to dev, just call MenuDrawer#setOnInterceptMoveEventListener

**Comment by Tolriq** [comment]
I'm sorry but the way you choose is not compatible with my need :(

This does work for a SeekBar but I use a CustomView that support gesture in all directions :(
In most of the case the menuDrawer will still trigger.

Actually even after testing the sample activity it does not work half of the times.

Edit 2 : In fact it seems that if you start the drag to left then move right the drawer does not trigger, but if you start the dragging to right first then the trigger will always start.

Perhaps the checks should be done on the DOWN and not the MOVE ?

**Comment by SimonVT** [comment]
It's pointless and expensive to do it on every down event. Unless the motion actually qualifies as a drag, the listener shouldn't be called. The listener only stops the drawer from intercepting the events, if it propagates up to onTouchEvent again it is going to start dragging. If your view does not handle the event, that is going to happen.
As far as I can see, it works as expected.

**Comment by Tolriq** [comment]
Well I'm sorry but I'm testing again your sample application :

You can click anywhere on the SeekBar to change it's value so it's OK.
You can press the thumb and move to the left to change the value while dragging this works ok and once you have started moving to the left you can then move to the right.
Now try to press the thumb and move to the right directly then the drawer activates.

This is clearly not the intended way it should work.

Tested on Nexus 7 4.2.2

**Comment by SimonVT** [comment]
Works fine now :)

**Comment by Tolriq** [comment]
Works much better :)

You may want to remove Log.d(TAG, "[onInterceptTouchEvent] child can scroll"); for release to avoid another oups commit :p

The last small problem (maybe on my side) is that if you start dragging over a view that handle this, and then continue dragging out of it to the right (there's padding on side of my gesture view) then the dragging will still start.

Is there a way to cancel this ? (Perhaps on the touch listener of the my gesture view?)

**Comment by Tolriq** [comment]
No idea ? This render the whole thing not usable ;(
