### ISSUE TITLE
I want to creat the menu like app of path on ios . left menu  and right menu

### ISSUE THREAD

**Issue by liufsd** [SimonVT/android-menudrawer#57]
Hey Simon/Jake

First of all, thanks for sharing your app menu drawer implementation.

I want to creat the menu like app of path on ios .  that have two menu for left and right in the mainactiviy  in the theam time.

But in your code,i found :  public MenuDrawerManager(Activity activity, int dragMode, int gravity) {
        mActivity = activity;
        mDragMode = dragMode;

```
    mMenuDrawer = gravity == MenuDrawer.MENU_POSITION_RIGHT ? new RightDrawer(activity) : new LeftDrawer(activity);
```

so, that's mean :your library can not do that. ?
Thanks/

**Comment by liufsd** [comment]
Let me know what you think. Thanks!

**Comment by SimonVT** [comment]
This is currently not possible, no.

**Comment by liufsd** [comment]
Why not?

**Comment by liufsd** [comment]
You can. see here: 
http://android.cyrilmottier.com/?p=701
But how to use your lib..for left and right in the theam time?

**Comment by liufsd** [comment]
It can: https://github.com/jfeinstein10/SlidingMenu

**Comment by SimonVT** [comment]
Because I haven't added it yet.

**Comment by liufsd** [comment]
how to do that?

**Comment by liufsd** [comment]
so,Today. just for left  menu,how can i  remain the left menu unchanged when i click menu item to intent new activity ?
I mean, the new activity have the theam left menu .
MainActiviy--leftmenu
SecondAcitity--leftmenu.

it looks facebook left menu or path left menu on ios,

in your code: if i write : 
 private AdapterView.OnItemClickListener mItemClickListener = new AdapterView.OnItemClickListener() {
        @Override
        public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
            mActivePosition = position;
            mMenuDrawer.setActiveView(view, position);
//            mContentTextView.setText(((TextView) view).getText());
            mMenuDrawer.closeMenu();

```
        Intent intent=new Intent(MainActiviy.this,SecondAcitity.class);
        startActivity(intent);
```

//  
        }
    };

But not ok ...... just a slow...  

so   what happened ?

Thanks a lot .

**Comment by liufsd** [comment]
@Ikram thanks. But base activity  looks back slowly..

**Comment by liufsd** [comment]
@iontech

**Comment by ghost** [comment]
I am not into much specifics of this. @SimonVT must have the apt response to this.

**Comment by liufsd** [comment]
@iontech  it looks like path on iOS . All the view just looks like have only one left menu.

**Comment by liufsd** [comment]
@iontech hi, what is your email address ? I will send some code ../
