### ISSUE TITLE
click menu item back mainview

### ISSUE THREAD

**Issue by liufsd** [SimonVT/android-menudrawer#58]
HI, When i click Menu item ,I want to change another activity stil the activity has the left menu .

   private AdapterView.OnItemClickListener mItemClickListener = new AdapterView.OnItemClickListener() {
        @Override
        public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
            mActivePosition = position;
            mMenuDrawer.setActiveView(view, position);
//            mContentTextView.setText(((TextView) view).getText());
            mMenuDrawer.closeMenu();

```
        //start new activity  
```

//
            Intent intent=new Intent(BaseActivity.this,CopyOfTestActivity.class);
            startActivity(intent);
//  
        }
    };

**Comment by SimonVT** [comment]
I don't understand the question.

**Comment by ghost** [comment]
From what I understand:

Currently we attach the **Menu Drawer** to an `Activity` and it is live only for that specific `Activity`.
@79144876 wants to attach the **Menu Drawer** once and persist it over multiple activities.

**Comment by liufsd** [comment]
yes。

**Comment by ghost** [comment]
@79144876, you can use `Fragment`s. `replace()` to a corresponding `Fragment` in `onItemClick()`.

If you're not comfortable with Fragments, you can create a base Activity implementing `setMenuView()` in `onCreate()` and then inherit this base Activity to create your app's Activities. In these Activities you can implement `setContentView()`.

**Comment by liufsd** [comment]
i mean, when I in the main activity ,and then click or sorrl to show left menu,
.so, at this time you click menu item ,it looks like the view back main activity at first, and then change main view layout.but this new activity should have a left menu.
The app looks like has only one left menu in all activitys.

**Comment by ghost** [comment]
@79144876 I don't think I understand it. Could you be a bit clear, please.

**Comment by SimonVT** [comment]
You can't "share" a view between several activities like that. You can pass its state in the intent if you wish, but you'll have to attach a new menu.

**Comment by liufsd** [comment]
I get it.i write a baseactivity .it have a left menu .all activitys extends it,just set contentview, but in fact ,it not ok, when you back ,it looks slow..
