### ISSUE TITLE
First Item Cutted

### ISSUE THREAD

**Issue by franrx** [SimonVT/android-menudrawer#59]
When i implement a menu bassed on scrollview, some times the was moved little up and the first item was cutted imposibiliting the correct use of the menu.

**Comment by SimonVT** [comment]
How are you using the drawer? On what platform versions does this happen? Any specific devices? Can it be reproduced? Is there a sample?

**Comment by franrx** [comment]
I'm using de menu based on a custom class that extends from ScrollView.

The error was present on versions from 2.2 to 4.1.2, i test it on some different devices, there isn't any error, and it's a bit random, because not always reproduce de error.

I put an image.
![cap_menu](https://f.cloud.github.com/assets/1868158/52994/0a889a92-5a3e-11e2-8889-d201a74d7164.png)

**Comment by SimonVT** [comment]
[This](https://github.com/SimonVT/android-menudrawer/blob/master/library/src/net/simonvt/widget/MenuDrawer.java#L865) code should ensure that it doesn't happen. I haven't had that issue myself, so you're gonna have to provide a sample that shows this behavior.

**Comment by franrx** [comment]
I provide you an example how i use your library, first the java class that control de scrollview

package com.test.dilbert;

import android.content.Context;
import android.util.AttributeSet;
import android.widget.ScrollView;

public class MenuScrollView extends ScrollView {

```
public interface OnScrollChangedListener {

    void onScrollChanged();
}

private OnScrollChangedListener mOnScrollChangedListener;

public MenuScrollView(Context context) {
    super(context);
}

public MenuScrollView(Context context, AttributeSet attrs) {
    super(context, attrs);
}

public MenuScrollView(Context context, AttributeSet attrs, int defStyle) {
    super(context, attrs, defStyle);
}

@Override
protected void onScrollChanged(int l, int t, int oldl, int oldt) {
    super.onScrollChanged(l, t, oldl, oldt);

    if (mOnScrollChangedListener != null) mOnScrollChangedListener.onScrollChanged();
}

public void setOnScrollChangedListener(OnScrollChangedListener listener) {
    mOnScrollChangedListener = listener;
}
```

}

Now i put the layout that i use to draw menu

<?xml version="1.0" encoding="utf-8"?>
<com.test.dilbert.MenuScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/scrollView"
    android:background="#4b0000"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

```
<LinearLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical">

    <TextView
        android:id="@+id/home"
        android:gravity="center_vertical"
        android:padding="10dip"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:drawableLeft="@drawable/home"
        android:drawablePadding="10dip"
        android:background="@drawable/list_selector_holo_light"
        android:textSize="20sp"
        android:textColor="#FFFFFF"
        android:text="@string/menu_home" />

    <View
        android:layout_width="fill_parent"
        android:layout_height="2dip"
        android:background="#800000" />

    <TextView
        android:id="@+id/search"
        android:gravity="center_vertical"
        android:padding="10dip"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:drawableLeft="@drawable/search"
        android:drawablePadding="10dip"
        android:background="@drawable/list_selector_holo_light"
        android:textSize="20sp"
        android:textColor="#FFFFFF"
        android:text="@string/menu_search" />

    <View
        android:layout_width="fill_parent"
        android:layout_height="2dip"
        android:background="#800000" />

    <TextView
        android:id="@+id/most_popular"
        android:gravity="center_vertical"
        android:padding="10dip"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:drawableLeft="@drawable/popular"
        android:drawablePadding="10dip"
        android:background="@drawable/list_selector_holo_light"
        android:textSize="20sp"
        android:textColor="#FFFFFF"
        android:text="@string/menu_popular" />

    <View
        android:layout_width="fill_parent"
        android:layout_height="2dip"
        android:background="#800000" />

    <TextView
        android:id="@+id/favorites"
        android:gravity="center_vertical"
        android:padding="10dip"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:drawableLeft="@drawable/favourite_active"
        android:drawablePadding="10dip"
        android:background="@drawable/list_selector_holo_light"
        android:textSize="20sp"
        android:textColor="#FFFFFF"
        android:text="@string/menu_favorites" />

    <View
        android:layout_width="fill_parent"
        android:layout_height="2dip"
        android:background="#800000" />

    <TextView
        android:id="@+id/random"
        android:gravity="center_vertical"
        android:padding="10dip"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:drawableLeft="@drawable/random"
        android:drawablePadding="10dip"
        android:background="@drawable/list_selector_holo_light"
        android:textSize="20sp"
        android:textColor="#FFFFFF"
        android:text="@string/menu_random" />

    <View
        android:layout_width="fill_parent"
        android:layout_height="2dip"
        android:background="#800000" />

</LinearLayout>
```

</com.test.dilbert.MenuScrollView>

And last the function to set the menu

private void setMenu() {
        menuDrawer = new MenuDrawerManager(this, MenuDrawer.MENU_DRAG_WINDOW);
        menuDrawer.setContentView(R.layout.home);
        menuDrawer.setMenuView(R.layout.menu);

```
    MenuScrollView msv = (MenuScrollView) menuDrawer.getMenuView();
    msv.setOnScrollChangedListener(new MenuScrollView.OnScrollChangedListener() {
        @Override
        public void onScrollChanged() {
            menuDrawer.getMenuDrawer().invalidate();
        }
    });

    getSupportActionBar().setHomeButtonEnabled(true);
    getSupportActionBar().setIcon(R.drawable.menu);

    findViewById(R.id.home).setOnClickListener(this);
    findViewById(R.id.search).setOnClickListener(this);
    findViewById(R.id.most_popular).setOnClickListener(this);
    findViewById(R.id.favorites).setOnClickListener(this);
    findViewById(R.id.random).setOnClickListener(this);

    SharedPreferences sharedPreferences = getSharedPreferences("preferences", MODE_PRIVATE);
    boolean first = sharedPreferences.getBoolean("first", true);
    if(first) {
        String path = Environment.getExternalStorageDirectory().getAbsolutePath();
        File dir = new File(path + "/DilbertTest");
        if(!dir.exists()) {
            dir.mkdirs();
        }

        menuDrawer.getMenuDrawer().peekDrawer();
        SharedPreferences.Editor editor = sharedPreferences.edit();
        editor.putBoolean("first", false);
        editor.commit();
    }
}
```

the variables that you think not declarated are global variables.

Thank you for your help

**Comment by SimonVT** [comment]
Please provide a full project I can load up in my ide and run to see the issue. You could be doing all kinds of other strange things I don't know about, which could be causing the issue.

**Comment by Shusshu** [comment]
I have the same problem on my project

I use a MenuDrawer on the right in a fragment.

Funny thing is when I turn my phone to landscape it looks fine, and when I come back to portrait it's fixed.

I'm investigating it right now in my closed source app.

edit :
couldn't fine the reason :(

**Comment by Shusshu** [comment]
How can I do menuDrawer.setContentView() when I'm attaching the menuDrawer while inside a fragment ?

**Comment by ramdroid** [comment]
The problem is that you are not initializing the menu drawer in Activity.onCreate(). Make sure to have the following lines in there:

```
mMenuDrawer = MenuDrawer.attach(this, MenuDrawer.MENU_DRAG_WINDOW);
mMenuDrawer.setContentView(R.layout.activity_windowsample);
mMenuDrawer.setMenuView(R.layout.menu_scrollview);
```

**Comment by Shusshu** [comment]
Yes I do have that.

But the problem just dissappearred...

**Comment by SimonVT** [comment]
Will re-open when a complete sample that shows this behavior is provided.

**Comment by syrinekick** [comment]
i have the same problem , i have an Activity that initialise the menu drawer and 2 activities that inherit from it .
(i use actionbarshelock also , so it's a window dragging)
the way to reproduce for me is =
the first activity no problem withe menu drawer, 
access to second activity no problem( you have to open it in the second activity)
return to the first and then you can see the first item cut.
i'm in production code so if you have suggestion for this problem don't hesitate . need help please :)
thank you for all effort (french background so sorry for the bad english)
