### ISSUE TITLE
How to set activities into contentView

### ISSUE THREAD

**Issue by xiwang0826** [SimonVT/android-menudrawer#60]
Dear sir,

I am going to implement facebook style menu.  I searched a lot s of libraries for it and found this library is best.
But I have small issue for integrating with my project.
My project has already many FragmentActivityies. I am going to switch these activities using flyin menu. But I dont know how to set activities into contentView of ManuDrawer as view.

Please help me.
Regards,
Wang.

**Comment by SimonVT** [comment]
Using activities as content has been deprecated for about 2 years, use fragments instead.
