### ISSUE TITLE
[feature request] Add ability to display hint, showing the user how to slide the drawer open 

### ISSUE THREAD

**Issue by levinotik** [SimonVT/android-menudrawer#7]
It'd be nice to have the ability to display some sort of hint (maybe that's just displayed once) that shows the user that they can slide on the window to open the menu drawer.

**Comment by pommedeterresautee** [comment]
There is a project on Github called ShowcaseView (https://github.com/Espiandev/ShowcaseView) which use the ICS Launcher way to give tip. Unfortunately it doesn't work with Actionbar right now. So no way to circle the slider button, but I imagine it could be improved.

In my own app, I open the sidebar at the first launch, so I m sure every one has seen it.

**Comment by SimonVT** [comment]
There's no way of getting the size of the action bar icon, so that approach wont work.

I'm going to be implementing a method that slightly opens the drawer, then closes it again, as well as add a sample which shows how to do this until the user e.g. opens the drawer completely.

I kind of want to add an overlay that visually shows the touch area, as well as the direction of the drag. I'm not sure how this should look, so if anyone has any ideas I'm open to them.

**Comment by pommedeterresautee** [comment]
May be a red flashing vertical line on the left side? During 2/3 seconds. It will help the user to understand the bezel movement.

**Comment by SimonVT** [comment]
Just having a line blinking doesn't really tell the user they have to drag to open the drawer. There needs to be an arrow or something as well, and maybe some text. I just have no idea how to design it so it looks simple and pretty.

**Comment by pommedeterresautee** [comment]
You are right a vertical line indicate there is something in this place but not what to do.
To improve things you can make the bar flashing, but at each flash you make the bar appear slightly more on the right direction. It would appear and disappear progressively. I don't know if I m clear, but the result would be a vertical bar flashing and moving slightly to the right side. This progressive translation would make clear to the user that he has to make a movement from left to right. If you start this little animation just after you automatically slightly open the menu at the first launch it would be obvious that there is a menu and to open it you have the bezel movement.

To finish, making logo icon in the actionbar flashing would indicate this is another way to open the menu.

No need of text description, arrow...

**Comment by levinotik** [comment]
Hmm, I think @SimonVT is totally right to think about this carefully. I'm just wondering, do you see anything wrong with simply sliding the drawer open with an arrow pointing in the direction of the movement? You could even have an image of a finger there, though that seems kinda corny and not sure how you feel about being very opinionated or boxing clients into a very specific UI when it comes to putting that into a library. 

But yeah, just slide the drawer open to the right at a speed that is sort of indulgent (for lack of a better word). A speed that sort of looks/feels like a gesture so that it's super clear that this is an illustration and not some random drawer opening up inexplicably.

**Comment by pommedeterresautee** [comment]
FYI I am using this function on my app, and it works very well! The delay argument is very useful.

**Comment by pommedeterresautee** [comment]
Did you see this library?
https://github.com/stephanenicolas/RoboDemo

May be it can help...
