### ISSUE TITLE
Issues With TabActivity and Preference Activity

### ISSUE THREAD

**Issue by thetutlage** [SimonVT/android-menudrawer#70]
First of all it is a great library but i am having issues while implementing it with TabActivity and Preference Activity.

With TabActivity the drawer itself does not shows up but with Preference Activity it hides my preferences view.

**Comment by SimonVT** [comment]
TabActivity is deprecated, PreferenceActivity is just a ListActivity. There's a sample for that.

**Comment by thetutlage** [comment]
Yeah i have seen into it, thanks for library and quick response
