### ISSUE TITLE
Glitches while opening menu-drawer

### ISSUE THREAD

**Issue by akshaydeo** [SimonVT/android-menudrawer#71]
Hello,  first of all great job !!

I am using menu drawer with a custom layout as 

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    android:id="@+id/activity_dashboard_menu_drawer_view"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

<TextView android:id="@+id/activity_dashboard_login_category"
          android:layout_width="match_parent"
          android:layout_height="wrap_content"
          android:drawableLeft="@drawable/facebook_menudrawer_icon"
          android:text="@string/activity_dashboard_login_category"
          style="@style/MenuDrawerCategoryStyle"/>

<LinearLayout
        android:id="@+id/activity_dashboard_menu_drawer_app_category_filter"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal">

</LinearLayout>

<main.java.com.appsurfer.views.components.MenuView
        android:id="@+id/activity_dashboard_menu_drawer_menu_view"
        android:layout_width="match_parent"
        android:layout_height="fill_parent"/>
```

</LinearLayout>

And in code i use a custom base list adapter to update the elements  of the menudrawer

```
 private void prepareMenuDrawer() {
    // Initialize menu drawer manager
    mMenuDrawer = MenuDrawer.attach(this, MenuDrawer.MENU_DRAG_CONTENT);
    mMenuDrawer.setContentView(R.layout.activity_dashboard);
    // initialize menu view
    LinearLayout menuDrawerLayout = (LinearLayout) getLayoutInflater().inflate(R.layout.activity_dashboard_menu_drawer_view, null);
    MenuView menuView = (MenuView) menuDrawerLayout.findViewById(R.id.activity_dashboard_menu_drawer_menu_view);
    menuView.setAdapter(getMenuListAdapter());
    menuView.setOnScrollChangedListener(new MenuView.OnScrollChangedListener() {
        @Override
        public void onScrollChanged() {
            mMenuDrawer.invalidate();
        }
    });
    // Initialize menu drawer manager
    mMenuDrawer.setMenuView(menuDrawerLayout);
}


private MenuListAdapter getMenuListAdapter() {
    MenuListAdapter menuListAdapter = new MenuListAdapter(mContext, mHandler);
    // creating array list of menu
    ArrayList<MenuItem> menuItems = new ArrayList<MenuItem>();
    menuItems.add(new MenuItem(0, "Login", 0, MenuItem.MenuItemType.CATEGORY));
    menuItems.add(new MenuItem(1, "Title", 0, MenuItem.MenuItemType.TITLE));       
    return menuListAdapter;
}
```

But with this code, there is a visible hick up while opening and closing the menu drawer. I mean if i am opening the menu bar at the start it stops and then the movement is fine and smooth. 

I thought it might be because of adapter, but without setting the adapter if I open a blank menu drawer still issue is there.  I am building for the min sdk 8 and target sdk 12. Can you help me on this ?

**Comment by SimonVT** [comment]
Is it a small delay when opening the drawer for the first time, every time, or?
What API level are you running this on?

**Comment by akshaydeo** [comment]
The small delay is every time I open the drawer. I am testing this on Samsung Galaxy note 2, HTC one x, S3 and nexus s. All the devices show this behavior. All of them are API 16+.

**Comment by akshaydeo** [comment]
And when I slowly drag till some distance (considerably more than a fling would drag) this runs smoothly.

**Comment by SimonVT** [comment]
Can I get you to supply a full sample which displays this behavior?

**Comment by akshaydeo** [comment]
should i mail you the code simonvt@gmail.com ?

**Comment by SimonVT** [comment]
You can just link it here

**Comment by akshaydeo** [comment]
Ok this is weird. When i excerpted out the code related with menu drawer into the new app it works fine without any glitch. I feel its issue at the my end.

**Comment by akshaydeo** [comment]
Apparently It was issue related with theme 
android:theme="@style/Theme.Sherlock.Light.DarkActionBar"

When I removed in my main app it started working smoothly. Is this a known issue ??

**Comment by SimonVT** [comment]
I don't have any issues with the DarkActionbar theme.

**Comment by tiwadara** [comment]
![capture](https://f.cloud.github.com/assets/5197741/1103913/2d7a3852-18d0-11e3-818e-6df3269402a5.JPG)
![capture1](https://f.cloud.github.com/assets/5197741/1103915/2dd9288a-18d0-11e3-9533-7dd3bce305a7.JPG)

I am also having this same issue, even on the emulator
