### ISSUE TITLE
Right menu slides on top of the main content

### ISSUE THREAD

**Issue by akshaydashrath** [SimonVT/android-menudrawer#76]
This is more of a new feature request( maybe something to consider in the library roadmap). If you take a look at the new Google+ app the notifications slide out from the right on top of the fragment, which makes more sense for a right menu considering its more of an extension drawer rather than a navigation menu.

**Comment by gnuhel** [comment]
That would be a great feature. Hope you can integrate it.

**Comment by JakeWharton** [comment]
The menu drawer works on arbitrary `ViewGroup`s so this is already possible.

**Comment by SimonVT** [comment]
There are already other libraries that does this, like ribbonmenu.
