### ISSUE TITLE
Change the duration of the opening / closing animation

### ISSUE THREAD

**Issue by pommedeterresautee** [SimonVT/android-menudrawer#77]
Hi,

I am searching a way to accelerate the animation of the side menu.

I have searched in the source code and found that there is no real Android animation, the opening - closing is done in method animateOffsetTo().

So, is it possible to add a setter to velocity, as it will produce the effect I want.

Better would be a way to give the time in ms.

``` java
 protected void animateOffsetTo(int position, int velocity, boolean animate) {
        endDrag();
        endPeek();

        final int startX = (int) mOffsetPixels;
        final int dx = position - startX;
        if (dx == 0 || !animate) {
            setOffsetPixels(position);
            setDrawerState(position == 0 ? STATE_CLOSED : STATE_OPEN);
            stopLayerTranslation();
            return;
        }

        int duration;

        velocity = Math.abs(velocity);
        if (velocity > 0) {
            duration = 4 * Math.round(1000.f * Math.abs((float) dx / velocity));
        } else {
            duration = (int) (600.f * Math.abs((float) dx / mMenuSize));
        }

        duration = Math.min(duration, DURATION_MAX);

        if (dx > 0) {
            setDrawerState(STATE_OPENING);
            mScroller.startScroll(startX, 0, dx, 0, duration);
        } else {
            setDrawerState(STATE_CLOSING);
            mScroller.startScroll(startX, 0, dx, 0, duration);
        }

        startLayerTranslation();

        postAnimationInvalidate();
    }
```

I added code so every reader may understand how things work.

Regards

**Comment by SimonVT** [comment]
I guess i could add a setter for DURATION_MAX, it doesn't really make sense to add one for velocity.

**Comment by pommedeterresautee** [comment]
You are right! I was searching a way to accelerate things and I have
understood velocity act like a coefficient on the speed of the movement and
I was aware it should not really produce the exact thing I need but I
didn't got better idea.

Your idea exactly corresponds to what I need.

Thank you

**Comment by SimonVT** [comment]
Added and released.
