### ISSUE TITLE
Menu Partially Open ?

### ISSUE THREAD

**Issue by xlf14** [SimonVT/android-menudrawer#79]
Is it possible to have the menu partially open ? For tablets in portrait mode, I would like a small part of the menu to be always visible. ie. On open/drag, it should open to the full menu width desired. On close, it should still show part of the menu. Is this possible ? 
Excellent slide out nav btw.

**Comment by SimonVT** [comment]
Nope, this is not possible

**Comment by xlf14** [comment]
Thanks for your response Simon.vAny possibility of adding it in as a feature request ?

**Comment by SimonVT** [comment]
I don't think I'll be adding this.
