### ISSUE TITLE
The content of menudrawer gets out beyond the screen with FEATURE_ACTION_BAR_OVERLAY

### ISSUE THREAD

**Issue by shaubert** [SimonVT/android-menudrawer#8]
Drag mode was set to window.

The problem seems to be at MenuDrawer.onMeasure() method:

@Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
    ...
        if (mDragMode == MENU_DRAG_WINDOW) {
            View v = mContentView.getChildAt(0);
            final int topPadding = v.getPaddingTop();
            mMenuContainer.setPadding(0, topPadding, 0, 0);
}

topPadding equals to 25dp (status bar height?) without FEATURE_ACTION_BAR_OVERLAY, and 0 with FEATURE_ACTION_BAR_OVERLAY. But the contentView (android.R.id.content) gets topMargin=25dp when FEATURE_ACTION_BAR_OVERLAY is requested.
In case of FEATURE_ACTION_BAR_OVERLAY a decor view (getWindow().getDecorView()) is instance of ActionBarOverlayLayout (for API 16). That layout overrides fitSystemWindows(Rect insets) method and applies the insets for a content view. Maybe the MenuDrawer should contains such logic too.

**Comment by SimonVT** [comment]
Thanks for letting me know! I have been looking for a better way of getting the size of the status bar, and fitSystemWindows(Rect) is just what I needed.

**Comment by shaubert** [comment]
Glad to help. Thanks for your project!
