### ISSUE TITLE
Rendering problem with WebView in content.

### ISSUE THREAD

**Issue by ronnerberg** [SimonVT/android-menudrawer#80]
Hi!
I am having some trouble with the content not rendering correctly when closing the drawer.
Specifically when the content area contains a WebView. When i close the drawer, the part of the WebView that was not visible is just black during the closing animation / while I am holding the drawer.

I have tested on Samsung Galaxy S3 (GT-19300, Android ver. 4.1.2) and HTC Wildfire S (A510e, Android ver. 2.3.5). The SGS3 have this problem with & without the actionbar but the wildfire only have the problem with (ActionBarSherlock).

It seems as the WebView is not redrawn correctly and I seem to be able to fix this problem by adding 

```
mContentContainer.invalidate();
```

to the onOffsetPixelsChanged method. Like this:

```
@Override
protected void onOffsetPixelsChanged(int offsetPixels) {
    if (USE_TRANSLATIONS) {
        mContentContainer.setTranslationX(offsetPixels);
        offsetMenu(offsetPixels);
        invalidate();
        mContentContainer.invalidate();
    } else {
        mContentContainer.offsetLeftAndRight(offsetPixels - mContentContainer.getLeft());
        offsetMenu(offsetPixels);
        invalidate();
        mContentContainer.invalidate();
    }
}
```

Any ideas on this problem, possible solution? 
# Illustation

Drawer open, no problem:
![1](https://f.cloud.github.com/assets/2463227/179839/1a42abf8-7c12-11e2-9db9-4bf9e69b6f81.png)

Started closing the drawer, WebView not updated:
![2](https://f.cloud.github.com/assets/2463227/179840/1f51e938-7c12-11e2-88a7-4d330c39b598.png)
# Code to reproduce

Activity:

```
public class MainActivity extends Activity{
    private static final String TAG = "TEST";

    private MenuDrawer drawer;
    private WebView webView;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Log.i(TAG, "onCreate");
        setupDrawer();
        setupWebView();
    }

    private void setupDrawer(){
        Log.i(TAG, "setupDrawer");
        drawer = MenuDrawer.attach(this, MenuDrawer.MENU_DRAG_CONTENT,   Position.LEFT, false);
        drawer.setContentView(R.layout.main);
        drawer.setMenuView(R.layout.drawer_menu);
    }

    private void setupWebView(){
        Log.i(TAG, "setupWebView");
        webView = (WebView) findViewById(R.id.web_view);
        webView.loadUrl("http://www.google.se/");
    }
}
```

Drawer menu layout:

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="fill_parent"
              android:layout_height="fill_parent">
</LinearLayout>
```

Content layout:

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:orientation="vertical"
              android:layout_width="fill_parent"
              android:layout_height="fill_parent"
        >

    <WebView
            android:id="@+id/web_view"
            android:layout_width="fill_parent"
            android:layout_height="fill_parent"
            />
</LinearLayout>
```

Manifest:

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="2" android:versionName="1.0.0-SNAPSHOT" package="com.drawer.test">

    <uses-sdk android:minSdkVersion="8" android:targetSdkVersion="16"/>
    <uses-permission android:name="android.permission.INTERNET"/>

    <application android:icon="@drawable/icon" android:theme="@android:style/Theme.DeviceDefault.Light.NoActionBar">
        <activity android:label="@string/app_name" android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
</manifest>
```

**Comment by wisedog** [comment]
@ronnerberg  
I also faced same problem. Some devices are working well but some devices do not work well. 
Use 

``` java
WebView.setLayerType(View.LAYER_TYPE_SOFTWARE, null); 
```

It works well in my case.

**Comment by ronnerberg** [comment]
@wisedog 

Thank you! I will try that out.

**Comment by xiaoym** [comment]
@wisedog 

So many thanks. but setLayerType only available after api level 11, any other solutions?

**Comment by ronnerberg** [comment]
@wisedog 
Thank you! That seemed to solve the problem.
@xiaoym 
You can do a check, like this:

``` java
if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB)
    webView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
```

The problem seems to be caused by the new rendering pipeline introduced in Android 3.0 where Views no longer redraw child views when invalidated. This is just my theory, any confirmation/correction is welcome.

I found a great [Google I/O talk](http://youtu.be/v9S5EO7CLjo) about the new rendering pipeline.
