### ISSUE TITLE
onCreateContextMenu does not work

### ISSUE THREAD

**Issue by pietronaccari** [SimonVT/android-menudrawer#85]
Hi, I was trying the Menu Drawer combined with a ListView, but I realized that the long press of a list item context menu does not open anymore, I tried to add a context menu to test the sample code attached to the library, but even there the context menu does not open, wrong in something, thank you.

**Comment by SimonVT** [comment]
I don't know, I don't change how ListView works. You could just add a long click listener, context menu seems like an outdated approach.
