### ISSUE TITLE
Side menu + Fragment + BackStack -> Good practice?

### ISSUE THREAD

**Issue by pommedeterresautee** [SimonVT/android-menudrawer#86]
Hi,

In my application, I use only fragments in one Activity.

So the side menu AND the main view are in the same activity.
For that purpose I am using menudrawer which works perfectly.

When a user click on an item in the side menu, I replace the fragment in the main view + I add the precedent one to the BackStack. So when the user press precedent, he goes to the precedent Fragment.

In a "no side menu" application, you can't go indefinitely deeper and deeper in the hierarchy of the application because there is a point where the dev has not implemented another subscreen, to go somewhere else, you will need to press precedent button and clean part of the back stack so its size in memory is always limited by the structure of the application, right?

But in an application with a side menu, you can click one hundred times on several menu items, and your backstack will increase by one hundred fragments, and  in particular on some old device, memory is not indefinite. 

Moreover if a user wants to quit the application by clicking precedent button, it has to be done in less than one hundred clicks.

In my application, I have set a counter, if precedent button is clicked more than 4 times in a row without switching of screen through the side menu in between, the activity is finished.

So even if the "quit" issue is fixed, the memory issue is not.

As you know, there is no way to remove first fragments from the stack, you can only pop the last one or erase every thing.

So, here is the question: What can I do to not use indefinite memory????

If you are curious to see how memory increases, have a look to my application:
https://play.google.com/store/apps/details?id=com.pommedeterresautee.twoborange3

There is a "Task killer" screen (no automatic task killer, just stop a selected task / service) showing the memory used. You will see it increases with time, more you swith to new fragments with the side menu, bigger the application become.

I am open to any sort of advice / solution.

Regards

**Comment by SimonVT** [comment]
The back button shouldn't switch between menu entries, just like the back button doesn't switch between tabs. They're all top level screens. Within each menu entry you can use the back stack functionali .

**Comment by pommedeterresautee** [comment]
I understand your point of view, and I shared it in the past. In previous version it was acting like that, but since I got tons of email / blog review asking / advising me to implement the precedent button. So now I do it. Users are expecting that behavior, whatever is in the Android Guidelines.

You have no idea how to manipulate the stack?

Regards

**Comment by SimonVT** [comment]
The behavior is pretty well defined by apps like Facebook, g+ and YouTube. I doubt users who are familiar with the platform expect any other behavior. If blogs are asking you to do this, they honestly have no business reviewing android apps.
