### ISSUE TITLE
drawArrow - checking parent

### ISSUE THREAD

**Issue by lsuski** [SimonVT/android-menudrawer#87]
In method LeftDrawer#drawArrow and RightDrawer#drawArrow there is line checking if parent of the active view is not null. It is OK when active view is  a root view of single item in the list (before adding it to hierarchy). But when you try to set as active view a child of that single item view then it causes Exception in method ViewGroup#offsetRectBetweenParentAndChild because parent is search recursively.

**Comment by SimonVT** [comment]
Thanks, I just fixed this on dev.
