### ISSUE TITLE
mdActiveIndicator not showing with HeaderView present

### ISSUE THREAD

**Issue by khawye** [SimonVT/android-menudrawer#88]
Hey,

I was wondering if there was a way to still display the arrow to indicate which listview item was selected when mList.addHeaderView is called.

I commented out all of the header code and the arrow was displayed as expected so I was wondering if there was something I did wrong.

The exact line of code that adds the header is as follows
        mList.addHeaderView(getLayoutInflater().inflate(R.layout.contact_card,null), null, false);

I wondered if the header pushes the indicies of the items down but i noticed that it didn't affect their position in the MenuAdapter so i'm stumped.

Thanks in advance for any insight.

**Comment by SimonVT** [comment]
Could you try the dev branch? I just made a few changes. If it still doesn't work, please provide a full sample (preferably as a zip I can download).

**Comment by khawye** [comment]
Ok I will give that a shot!

thanks for the reply

**Comment by khawye** [comment]
It still happens with the dev branch. I'll zip up the project and drop you a link. I'm make a simplified version for ease of use

**Comment by SimonVT** [comment]
Remember to offset the position from your OnItemClickListener by https://developer.android.com/reference/android/widget/ListView.html#getHeaderViewsCount()

**Comment by khawye** [comment]
Thanks! I feel like it is something to do with an offset and when i add the header it shifts the indicies of the menu items down or something. 

Perhaps i'm also not using the headerview as intended. How do i upload a zipfile to this, or should i just drop box it?
