### ISSUE TITLE
Responsive Layout

### ISSUE THREAD

**Issue by swanhtet1992** [SimonVT/android-menudrawer#89]
I'm trying to attach MenuDrawer as responsive menu for fragments. But I still can't attach it correctly. Here is what I wanted to do,
- Both on phones and tablets, the MenuDrawer will be attached as hidden in portrait mode.
- In landscape mode, the MenuDrawer will be attached as static to dual pane layout.

Is there any way to accomplish this?

**Comment by SimonVT** [comment]
if (portrait) {
    // attach as hidden
} else {
    // attach as static
}
?

**Comment by swanhtet1992** [comment]
Ah, yes. I already thought like that too. But it didn't work out.

**Comment by swanhtet1992** [comment]
Oops! Sorry. It works now.
I thought that I only need to initialized MenuDrawer#setContentView once outside of the condition.

Btw, How do you think which value is the best suite for MenuDrawer#setMenuSize in Landscape mode? Can it be set depending on screen_density?
