### ISSUE TITLE
[Feature Request] - Use multiple drawers at once

### ISSUE THREAD

**Issue by sniderzero** [SimonVT/android-menudrawer#90]
Can you include the ability to use multiple drawers at once, like a left drawer and bottom drawer in the same activity?

Thanks - great library!

**Comment by SimonVT** [comment]
You can use it as a regular view, I don't see why you shouldn't be able to put one inside another. I won't be adding any helper methods for this tho.

**Comment by sunilrana** [comment]
I tried it by using two menu view. but it overrides  the last view i added.
