### ISSUE TITLE
menudrawer with activities and fragments

### ISSUE THREAD

**Issue by avenkatesan** [SimonVT/android-menudrawer#91]
I was wondering if you have an example of how to integrate your library with existing projects that contain multiple activities and use fragments. For instance, in your Content Change example, when an item on the left is selected, the textView is set on the right. However, how do I handle the case when I need to create an activity for each menu item selection and display that activity on the right? This scenario is closer to real world apps and an example may help faster adoption of your excellent library!

Any help is greatly appreciated.

**Comment by SeanPONeil** [comment]
If you want to create a new Activity when an item is selected it's a simple startActivity(), unless I'm not understanding something. To change Fragments, you would create a new FragmentTransaction in the ClickListener for the menu item and do a replace().

**Comment by avenkatesan** [comment]
If a new activity is started, IMO, the slide out effect will not be shown correctly - the activity's creation process (and its initial view) will replace the entire Android screen and the effect will be weird.

In the example, the sliding menu's onClick handler renders a text view (AdapterView.OnItemClickListener) as shown below:
            mMenuDrawer.setActiveView(view, position);

My question is: on click of a menu item, if a NEW ACTIVITY is to be created and its view to be shown, how to handle this case, while keeping the sliding menu functionality intact?

**Comment by SeanPONeil** [comment]
A new Activity will replace the entire Android screen, by design, when startActivity() is called. Do you want the menu to close and then the Activity to start? If so, you might have a better time with Fragments.

**Comment by avenkatesan** [comment]
I want the exact same effect as the ContentSample.java (i.e.) the main view of the (newly created) activity should slide in and hide the menu. 

To provide more context: in my existing app, there are a few key workflows, each of which is an item on the sliding drawer menu. The menu needs to be accessible from all screens in the app. When user selects a menu item, an activity containing the initial UI for the selected workflow should open. Then, when the user selects a different menu item, another activity containing the initial UI for the second workflow should open.

When opening these new activities, i am trying to get the exact same effect as the Content sample  Is this possible with my existing app design? Or is it true that the only way to use this library is to organize all my views as fragments and have one main activity drive them (sounds impractical for a large app)?

**Comment by SeanPONeil** [comment]
If you want the same menu drawer to be accessible from all "screens" in the app, you are going to want to use Fragments.

**Comment by avenkatesan** [comment]
You mean - have a single activity for the entire app, which switches fragments in and out, depending on the sliding menu selection?

**Comment by SeanPONeil** [comment]
If you need to have the menu drawer available for all Fragments and keep the close animation as well. If some Activities don't have a menu drawer, and use the home button to go "up", for example, it isn't a bad thing and may help your users navigate around your app.

**Comment by SimonVT** [comment]
You could wait until the drawer is closed before you start the new activity. But yeah, use fragments. For the top level at least.

**Comment by RagingRiver** [comment]
I would like to have the MenuDrawer always available also.  Is this something you would consider changing?

**Comment by SeanPONeil** [comment]
You can have it always available right now if you want to, there's nothing to change.

**Comment by RagingRiver** [comment]
I was comparing to the article by Cyril Mottier on Prixing app.  Having the
menu available from multiple activities seems to be supported.

**Comment by SimonVT** [comment]
It's a view, you can't share/pass views between activities. You have to attach the drawer to each of them.
