### ISSUE TITLE
More than one drawer to slide back?

### ISSUE THREAD

**Issue by chasden** [SimonVT/android-menudrawer#95]
I'm trying to implement the menu-drawer using separate XML layouts for the left menu and the activity. What I'm seeing is that I need to pull 2 drawers back in order to actually see the menu items in the drawer... The first drawer is completely blank. Once I slide the next one back then the menu items are revealed.
![dual_drawers](https://f.cloud.github.com/assets/1320592/282704/d0e3b32e-9199-11e2-9fbd-942b9ff7061f.png)

Here's the activity code:
![Screen Shot 2013-03-20 at 4 08 25 PM](https://f.cloud.github.com/assets/1320592/282712/05f21d94-919a-11e2-8949-ac8e7b1a2718.png)

Here's the activity layout XML:
![Screen Shot 2013-03-20 at 4 10 24 PM](https://f.cloud.github.com/assets/1320592/282722/58608f52-919a-11e2-889d-d0b748e5bcd1.png)

Here's the menu layout XML (a fragment of it, anyway):
![Screen Shot 2013-03-20 at 4 12 40 PM](https://f.cloud.github.com/assets/1320592/282731/a4fd142a-919a-11e2-8c4a-0524b3de1bb1.png)

Any help or advice would be much appreciated!

Regards,

Charles

**Comment by SimonVT** [comment]
You're adding a drawer both from code and xml. Pick one.
