### ISSUE TITLE
Example of MenuDrawer content with Fragments

### ISSUE THREAD

**Issue by rcristobalm** [SimonVT/android-menudrawer#96]
I need a Example of MenuDrawer content with Fragments

Thank you

**Comment by SimonVT** [comment]
getFragmentManager().beginTransaction().add(R.id.someId, mSomeFragment).commit();
You can get the id of the content container by calling MenuDrawer.getContentContainer().getId() if you do not wish to inflate your own layout.

**Comment by rcristobalm** [comment]
Hello. The truth is that I am not very good at fragments. What I do is that when I click on one of the menu items, change the part of the LEFT with another activity or fragment. How I can do that? I can pass a simple example?

Thank you very much.

greetings

**Comment by khaoulaHD** [comment]
Hello it's my first time working with fragments i want to integrate the menudrawer in my project while every item in the menu opens another fragment .How can i do it? i tried this :                                                    

---

private class SlideMenuClickListener implements
            ListView.OnItemClickListener {
        @Override
        public void onItemClick(AdapterView<?> parent, View view, int position,
                long id) {
            // display view for selected nav drawer item
            displayView(position);
        }
    }

```
@SuppressLint("NewApi")
private void displayView(int position) {
    Fragment fragment = null;

    switch (position) {
    case 0:
        fragment = new Fragment_test();
        break;
    case 1:
        fragment = new Fragmenttest();
        break;

    default:
        break;
    }

    if (fragment != null) {
        FragmentManager fragmentManager = getFragmentManager();

        android.support.v4.app.FragmentManager fragmentManager1 = getSupportFragmentManager();
         fragmentManager1.beginTransaction().replace(mMenuDrawer.getContentContainer().getId(),
    fragment).commit();

        // update selected item and title, then close the drawer
        mList.setItemChecked(position, true);
        mList.setSelection(position);
        mMenuDrawer.closeMenu();
        // mDrawerLayout.closeDrawer(mList);

    } else {
        // error in creating fragment
        Log.e("MainActivity", "Error in creating fragment");
    }
}
```

---

But nothing shows up only the contenttext.  Help me please !!!

**Comment by Elghazal** [comment]
@khaoulaHD Hi, i'm having same your problem, do you solve it ?
