### ISSUE TITLE
Reduce overdraw by removing DecorView background

### ISSUE THREAD

**Issue by UweTrottmann** [SimonVT/android-menudrawer#98]
I've been made aware by a user that DecorView seems to reset its background when attaching the drawer. As a "fix" it was suggested that I use something like

`getWindow().getDecorView().setBackgroundDrawable(null);`

which _does_ reduce overdraw of the whole window by one level (returning to the same level as it was before adding the drawer to the app).

I hope you can shed some light on this, maybe even improve the overdraw issue with android-menudrawer.

**Comment by SimonVT** [comment]
Setting windowBackground to @&#8203;null doesn't solve this?

**Comment by UweTrottmann** [comment]
Well, it would. But I want to set my own window background color in the app theme XML.

**Comment by DavidTPate** [comment]
I don't think this is something that should be done at the library level. Not all applications will want to set the background drawable to null and the library is not the gatekeeper to this value.

Instead this should be set at the application or activity level depending on your preference. Please see here for details: http://android-developers.blogspot.com/2009/03/window-backgrounds-ui-speed.html

If we wanted to do this to the Sample provided with Android Menu Drawer then we would simply add the following line to the SampleBase theme in res/values/themes.xml. This will set the background drawable for the window to null (or whatever else you set it to).

``` xml
<item name="android:windowBackground">@null</item>
```

For the whole edited file, see here: https://gist.github.com/DavidTPate/5462374

**Comment by SimonVT** [comment]
I'm going to pass on this one. I don't want to make any assumptions about the users desired behavior.
